### PR TITLE
run-treecompose: stick pkg diff into JSON

### PR DESCRIPTION
**Pull request by miabbott**

### CODE REVIEW

**Comment by miabbott** [comment]
Hmm...looking over at [coreos/coreos-assembler](https://github.com/coreos/coreos-assembler), maybe these kinds of changes should land over there.

**Comment by ashcrow** [comment]
> Hmm...looking over at coreos/coreos-assembler, maybe these kinds of changes should land over there.
/cc @cgwalters

**Comment by cgwalters** [comment]
> Hmm...looking over at coreos/coreos-assembler, maybe these kinds of changes should land over there.

Well yeah, we already did that in https://github.com/coreos/coreos-assembler/pull/59

**Comment by miabbott** [comment]
> Well yeah, we already did that in coreos/coreos-assembler#59

Right...that's still missing the package diff which this is providing.  Anyways, I'll make that change over there.

**Comment by cgwalters** [comment]
> Right...that's still missing the package diff which this is providing. 

That's in the rpm-ostree json right?

**Comment by miabbott** [comment]
> That's in the rpm-ostree json right?

picard-facepalm

Yeah...

/me sighs

**Comment by cgwalters** [comment]
To be fair it's going to be a little bit until we can deploy assembler...it can still make sense to do fixes to the existing one, but we have to measure the cost/benefit of changing it.

**Pull request closed without merging**
