### PR TITLE
Bug 2103053: ci: Rework to merge all scripts into one

### PR DESCRIPTION
**Pull request by travier**
Manual backports of changes from master:

- 8efbd98 ci: Merge all Prow CI "build" scripts into one
- 787d5da ci: Do not fail on rpm-ostree missing
- 5e9b2b2 ci: Regroup tests in qemu & metal buckets
- eb3a605 ci: Prepare and clean-up test names
- 0a70681 ci: Remove now unused scripts
- 3d4cf57 ci: Remove Dockerfiles (moved to release)
- a0e0483 ci/prow-entrypoint: No-op `cosa init` if already initialized
- 8cbb015 ci: Add an explicitly named test entry for COSA CI
- a193baf ci: Remove now unused test names

### CODE REVIEW

**Comment by travier** [comment]
Goes with https://github.com/openshift/release/pull/29949

**Comment by miabbott** [comment]
Looks like a chicken + egg problem here, so let's merge this first then https://github.com/openshift/release/pull/29949

/lgtm

**Comment by travier** [comment]
Let's try a retest first
/retest

**Comment by travier** [comment]
Sorry @miabbott, I was looking at other PRs. We should be able to merge this one over green CI.

**Review by mike-nguyen — APPROVED** [review]

**Pull request merged**
