### PR TITLE
c9s: Pull RPMs from CentOS Cloud SIG repo

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by travier** [comment]
Timeout :/

**Comment by LorbusChris** [comment]
The other SCOS build-test suceeded, maybe this was transient?
/test scos-9-build-test-qemu

**Comment by LorbusChris** [comment]
The build and qemu test worked fine on op1st:

https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/okd-team/tekton.dev~v1beta1~PipelineRun/okd-coreos-all-4.13-test-os-pr1297-pipelinerun-zs9hc/ (logs only available today)

We might have to bump the timeout if it occurs again?

**Comment by LorbusChris** [comment]
[cosa-test.log](https://github.com/openshift/os/files/11581546/cosa-test.log)

**Pull request merged**
