### PR TITLE
Switch back to RHEL 8.4 GA content

### PR DESCRIPTION
**Pull request by travier**
Revert "ci: Temporarily force 8.4 Beta repos"

This reverts commit 8ce67f32128b7fc966eb87454da83773f9e7aa02.

---

Revert "ci: Temporarily exclude Secure Boot testing"

This reverts commit af43105f4ce9db2e2a04fc3947b8bcf374e34a47.

### CODE REVIEW

**Comment by travier** [comment]
Hold until the advanced virt repos are updated in openshift/release
/hold

**Comment by travier** [comment]
https://github.com/openshift/release/pull/18691

**Review by darkmuggle — APPROVED** [review]

**Comment by travier** [comment]
Once we've merged this one, we should probably branch this repo for 4.8.

**Comment by cgwalters** [comment]
CI is good, are we actually blocked on https://github.com/openshift/release/pull/18691 or not?

**Comment by travier** [comment]
We are for advanced virt repos that require beta content

**Comment by travier** [comment]
https://github.com/openshift/release/pull/18691/files#diff-c67f594c084937c847dd5e47676ba4d13a918373df766576f9d17c26b82c76a4

**Pull request merged**
