### PR TITLE
Rename efi path and disable `podman.rootless-systemd` on c9s/rhel-9.0

### PR DESCRIPTION
**Pull request by HuijingHei**
- Rename EFI/redhat dir to EFI/vendor
    - The change in coreos-assembler is https://github.com/coreos/coreos-assembler/pull/3048
- denylist: disable `podman.rootless-systemd` on c9s/rhel-9.0
    - Enable `chrony.dhcp-propagation`, according to https://github.com/coreos/fedora-coreos-config/pull/1952

### CODE REVIEW

**Comment by HuijingHei** [comment]
/hold
This needs https://github.com/coreos/fedora-coreos-config/pull/1952 merged and sync to openshift/os

**Comment by HuijingHei** [comment]
https://github.com/coreos/fedora-coreos-config/pull/1952 is merged, the failed `podman.rootless-systemd` in https://github.com/openshift/os/pull/976 needs this PR
/unhold

**Comment by travier** [comment]
Moved into https://github.com/openshift/os/pull/978
/close

**Pull request closed without merging**
