### PR TITLE
OKD-220: Update c9s.repo to install cri-o 1.29.5

### PR DESCRIPTION
**Pull request by aleskandro**
Updating the repo to install the latest crio 1.29 for 4.16. the 4.17 repo is not available yet. This should be backported to release-4.16

/cc @travier

### CODE REVIEW

**Comment by travier** [comment]
We should not backport OKD changes to branch releases. Everything should be built from the master branch.

**Comment by travier** [comment]
Change LGTM but no backport.
/lgtm

**Comment by aleskandro** [comment]
The failure is about https://github.com/openshift/os/issues/1540

**Comment by aleskandro** [comment]
``` --- FAIL: ext.config.shared.networking.force-persist-ip (50.55s)
        harness.go:1823: mach.Start() failed: machine "fdb74dc7-2401-42d2-832a-99d4eff463f5" failed basic checks: detected failed or stuck systemd units: some systemd units failed: systemd-network-generator.service; <nil>
=== RUN   rpmostree.upgrade-rollback/rollback
--- PASS: rpmostree.upgrade-rollback (135.24s)
    --- PASS: rpmostree.upgrade-rollback/upgrade (53.24s)
    --- PASS: rpmostree.upgrade-rollback/rollback (41.65s)
--- PASS: ext.config.shared.networking.nmstate.state (76.11s)
--- PASS: rhcos.network.init-interfaces-test (176.85s)
--- PASS: coreos.ignition.failure (30.27s)
--- FAIL: ext.config.shared.networking.prefer-ignition-networking (41.61s)
        harness.go:1823: mach.Start() failed: machine "ccc3eb72-4873-4f85-b223-4de8e8ca3528" failed basic checks: detected failed or stuck systemd units: some systemd units failed: systemd-network-generator.service; <nil> 
 --- PASS: ext.config.shared.ignition.resource.remote (74.59s)
--- FAIL: ext.config.shared.networking.bridge-static-via-kargs (42.05s)
        harness.go:1823: mach.Start() failed: machine "0e06ddb3-9af2-46fe-b3d5-bf94d496b894" failed basic checks: detected failed or stuck systemd units: some systemd units failed: systemd-network-generator.service; <nil>
--- PASS: ext.config.shared
```

**Comment by jlebon** [comment]
Yeah, SCOS CI is broken right now as you see. I don't think we need to block on this.

/override ci/prow/scos-9-build-test-qemu

But as @travier said, this shouldn't be backported. It doesn't seem like there's a way to cancel a `/cherrypick` command, so we'll just have to close the PR it opens.

**Pull request merged**
