### PR TITLE
c9s: Add temporary COPR repo for openvswitch on s390x

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
CI here won't test that change.

**Comment by travier** [comment]
Arg, it's failing as we only have that for s390x 🙁

**Comment by jlebon** [comment]
I think you should be able to work around the arch issue by putting the repo addition in a separate manifest, and including it using an `arch-include` on s390x only.

Can you include a link to the email thread where this COPR repo is referenced by a CentOS NFV SIG team member in the commit message and also as a comment in the yum repo file?

**Comment by travier** [comment]
Closing in favor of https://github.com/openshift/os/pull/1127.

**Pull request closed without merging**
