### PR TITLE
Update for RHEL 8.6 Beta

### PR DESCRIPTION
**Pull request by HuijingHei**
Bump RHCOS to RHEL 8.6 Content

### CODE REVIEW

**Comment by ravanelli** [comment]
> ci/prow/build-test-qemu	[d53404b](https://github.com/openshift/os/commit/d53404b1ea427be814cb15d1f5b242b1c8de85a1)	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_os/756/pull-ci-openshift-os-master-build-test-qemu/1508755523808268288)	true	`/test build-test-qemu`
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=os&pr=756). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:HuijingHei).

Looks https://github.com/openshift/release/pull/27333 needs to get merged first in order to CI pass

**Review by ravanelli — APPROVED** [review]
LGTM

**Comment by miabbott** [comment]
/hold

for https://github.com/openshift/release/pull/27333 to be merged

**Comment by HuijingHei** [comment]
/hold cancel
https://github.com/openshift/release/pull/27333 is merged now, thanks all for the review

**Pull request merged**
