### PR TITLE
manifest: RHEL: Update OCP release to 4.13

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
CC @mike-nguyen (for branching)

**Comment by travier** [comment]
We need to wait for a response from OKD folks if we do that for OKD too right now or not.

**Comment by travier** [comment]
CC @LorbusChris @vrutkovs

**Comment by vrutkovs** [comment]
Safe to merge, we're pinned to a particular commit in machine-os-content

**Comment by LorbusChris** [comment]
/lgtm

SCOS for OKD/SCOS 4.12 will be built from the release-4.12 branch.

**Comment by travier** [comment]
> SCOS for OKD/SCOS 4.12 will be built from the release-4.12 branch.

Let's not do that then. We will not do backports for SCOS so we have to stay on the main branch here. I'll keep SCOS on 4.12.

**Comment by travier** [comment]
SCOS failures tracked in https://github.com/openshift/os/issues/1057

**Comment by travier** [comment]
Overriding as we're only changing RHEL based RHCOS here.
/override ci/prow/scos-9-build-test-qemu

**Review by ravanelli — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
This is failing on the 4.13 RHAOS repo timing out:
```
error: Updating rpm-md repo 'rhel-8-server-ose': cannot update repo 'rhel-8-server-ose': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for http://base-4-13-rhel86.ocp.svc.cluster.local/rhel-8-server-ose/repodata/repomd.xml [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
error: failed to execute cmd-fetch: exit status 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-11-09T10:36:16Z"}
```

**Comment by travier** [comment]
It looks like they are correctly defined in https://github.com/openshift/release/blob/master/core-services/release-controller/_repos/ocp-4.13-rhel86.repo

**Comment by jlebon** [comment]
Hmm, works fine locally both privileged and unprivileged. We need better error-prefixing in rpm-ostree. For now, I've pushed a temporary commit to help debug.
/hold

**Comment by jlebon** [comment]
This *should* be good to go now!
/hold cancel

**Comment by mike-nguyen** [comment]
:pray: @jlebon Thank you for fixing CI!

**Pull request merged**
