### PR TITLE
NO-JIRA: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Adam Piasecki (1):
      kola/kernel-replace: adapt for RHCOS and SCOS

Jonathan Lebon (6):
      manifests/fedora-coreos-base: re-add qed-firmware
      Revert "overlay/15fcos: upgrade bootloader for Secure Boot-enabled systems"
      Revert "overlay/15fcos: ensure valid aleph file"
      Revert "overrides: pin kernel-6.8.11-300.fc40"
      overlay/growfs: skip growpart on DASD disks
      overlay/growfs: use luksDump JSON output for analysis

Michael Armijo (3):
      denylist: snooze ssh.key until new afterburn release
      tests/ntp: use the FCOS defined fedora.repo to set up container
      tests/podman/rootless-systemd: use the FCOS defined fedora.repo to set up container

Timothée Ravier (2):
      fasttrack openssh-9.6p1-1.fc40.4
      coreos-ignition-setup-user: Remount before writing to /usr

jbtrystram (10):
      tests: kdump.crash enable more debugging in kdump service
      overlay/15fcos: ensure valid aleph file
      overlay/15fcos: upgrade bootloader for Secure Boot-enabled systems
      manifests: includes kdump subpackages in f40
      manifests: cleanup f39 conditional includes
      Revert "Denylist: add kdump.crash for ppc64le"
      denylist: add kdump.crash for aarch64
      denylist: add kdump.crash.ssh for aarch64
      Revert "denylist: add kdump.crash.ssh for aarch64"
      Revert "denylist: add kdump.crash for aarch64"

madhu-pillai (1):
      overlay/growfs: support CEX-encrypted LUKS volumes
```

### CODE REVIEW

**Review by jbtrystram — APPROVED** [review]
/lgtm

**Review by marmijo — APPROVED** [review]
/lgtm

**Review by marmijo — APPROVED** [review]
/lgtm
/retest

**Review by ravanelli — APPROVED** [review]

**Review by aaradhak — APPROVED** [review]

**Review by c4rt0 — APPROVED** [review]
/lgtm
/retest

**Review by c4rt0 — COMMENTED** [review]
/lgtm

**Comment by jlebon** [comment]
Looks like CI is back now! :tada: 

Filed https://github.com/openshift/os/issues/1564 for the CI failure.

**Comment by marmijo** [comment]
> Looks like CI is back now!

Yes, the DPTP team was able to resolve this for us today!

**Comment by jlebon** [comment]
CI should be fixed by https://github.com/openshift/os/pull/1565.

**Review by marmijo — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
