### PR TITLE
[release-4.13] bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by marmijo**
```
$ git -C fedora-coreos-config shortlog --no-merges 88d62812..af14f88e
Timothée Ravier (1):
      tests/validate-symlinks: Skip '/etc/pki/tls/'
```
See: https://github.com/coreos/fedora-coreos-config/pull/2532

### CODE REVIEW

**Review by gursewak1997 — APPROVED** [review]

**Comment by gursewak1997** [comment]
/label backport-risk-assessed
/label cherry-pick-approved

We either need a valid bug label override for this one or we have it land in an RHCOS boot image bump to satisfy the bot.

**Comment by mike-nguyen** [comment]
@mrunalp can you the override the jira/valid-bug label to this PR?  This is just picking up a test change.

**Pull request merged**
