### PR TITLE
treecompose: use `atomic-openshift-*` packages

### PR DESCRIPTION
**Pull request by miabbott**
This swaps out the use of `origin-*` packages for signed `atomic-openshift-*`packages produced by the ART team.

Currently, these are 3.11 packages, but once 4.0 versions are being produced by ART, we can switch to them.

The package diff is nicely contained:

```
ostree diff commit old: 0de27f731fcdedd767ea99e3b341065146b570628bf9d76d3d6837eb524550da
ostree diff commit new: fcae50fcd1c3339efbce808b29f34acce135c6e52b75c61942189666e5a9a3cb
Removed:
  origin-clients-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
  origin-hyperkube-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
  origin-node-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
Added:
  atomic-openshift-clients-3.11.16-1.git.0.b48b8f8.el7.x86_64
  atomic-openshift-hyperkube-3.11.16-1.git.0.b48b8f8.el7.x86_64
  atomic-openshift-node-3.11.16-1.git.0.b48b8f8.el7.x86_64
```

### CODE REVIEW

**Comment by miabbott** [comment]
Note, the original Jira ticket (COREOS-468) requested 4.0 packages, so this might have to wait until ART is generating them.

**Comment by cgwalters** [comment]
> Note, the original Jira ticket (COREOS-468) requested 4.0 packages, so this might have to wait until ART is generating them.

I can't say for sure but I'd be surprised if there wasn't some dependency on newer kubelet features at this point.

**Comment by ashcrow** [comment]
> I can't say for sure but I'd be surprised if there wasn't some dependency on newer kubelet features at this point.

Agreed. Once @tbielawa's group is producing 4 compat packages we can make the switch. Until then origin is the closest we have.

**Comment by miabbott** [comment]
OK I'll hold this until the 4.0 bits land.

**Comment by miabbott** [comment]
Latest commits switched to the 4.0 bits.  Got the following diff:

```
ostree diff commit old: 16b726488bf4e58c3d4175e5f96c73eb134452f5a1bbafeb5a0a30b47918de74
ostree diff commit new: fddbbfbf295002caf84f600ad9ce2a2a06367eeb008ead90b9f1dbeffd7db00c
Upgraded:
  python-setuptools 0.9.8-7.el7 -> 17.1.1-4.el7
Removed:
  origin-clients-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
  origin-hyperkube-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
  origin-node-4.0.0-0.alpha.0.9.8d6f6f3.x86_64
  python-requests-2.6.0-1.el7_1.noarch
  python-urllib3-1.10.2-5.el7.noarch
Added:
  atomic-openshift-clients-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
  atomic-openshift-hyperkube-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
  atomic-openshift-node-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
  pyOpenSSL-0.13.1-3.el7.x86_64
  python-cffi-1.6.0-5.el7.x86_64
  python-enum34-1.0.4-1.el7.noarch
  python-idna-2.4-1.el7.noarch
  python-ply-3.4-11.el7.noarch
  python-pycparser-2.14-1.el7.noarch
  python2-cryptography-1.7.2-2.el7.x86_64
  python2-pyasn1-0.1.9-7.el7.noarch
  python2-pysocks-1.5.7-4.el7.noarch
  python2-requests-2.14.2-1.el7ost.noarch
  python2-urllib3-1.21.1-1.el7.noarch
```

So....ew, more Python?

**Comment by miabbott** [comment]
I've warily lifted the hold...I'm curious what is dragging in all those python packages, but I don't think it would prevent this from being merged

**Comment by ashcrow** [comment]
Likely the specs for `atomic-openshift-*` have extra dependencies. I'm sure they were absolutely required at one point but probably are no longer required... we can help on that later :-)

**Comment by cgwalters** [comment]
Offhand I'm guessing those are dependencies Ansible needs on the host, or needed at one time.

**Comment by ashcrow** [comment]
One issue is it seems to be pulling 3.x packages still.

**Comment by miabbott** [comment]
> One issue is it seems to be pulling 3.x packages still.

```
Added:
  atomic-openshift-clients-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
  atomic-openshift-hyperkube-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
  atomic-openshift-node-4.0.0-0.7.0.git.0.d8687bf.el7.x86_64
```

Looks like 4.0 to me?

**Comment by ashcrow** [comment]
Oops, you're right. Sorry @miabbott!

**Pull request merged**
