### PR TITLE
common.yaml: add comment about when to drop usermod workaround

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]
/lgtm

**Comment by dustymabe** [comment]
This is just changing a comment. I'm going to ignore CI failures.

**Comment by dustymabe** [comment]
/override rhcos-92-build-test-qemu scos-9-build-test-metal scos-9-build-test-qemu

**Comment by dustymabe** [comment]
/override ci/prow/rhcos-92-build-test-qemu ci/prow/scos-9-build-test-metal ci/prow/scos-9-build-test-qemu

**Pull request merged**
