### PR TITLE
kola: Denylist `luks.*` on ppc64le

### PR DESCRIPTION
**Pull request by cgwalters**
See https://github.com/openshift/os/issues/1149

### CODE REVIEW

**Review by marmijo — APPROVED** [review]
LGTM

**Comment by cgwalters** [comment]
This one can bypass all CI here
/override ci/prow/rhcos-86-build-test-metal
/override ci/prow/rhcos-86-build-test-qemu
/override ci/prow/rhcos-90-build-test-metal
/override ci/prow/rhcos-90-build-test-qemu
/override ci/prow/scos-9-build-test-metal
/override ci/prow/scos-9-build-test-qemu

**Comment by cgwalters** [comment]
@marmijo Thanks for the review; in this repo with Prow enabled to merge it needs a `/lgtm` comment too

**Pull request merged**
