### PR TITLE
Bump fedora-coreos-config submodule

### PR DESCRIPTION
**Pull request by bgilbert**
Update Ignition to 2.8.1, support boot disk RAID, fix initrd logging of failed units and rootfs fetch errors, fix Afterburn checkin and hostname fetching on Azure, drop Perl dependency on s390x, increase transposefs mount logging, possibly fix race between rootfs restore and UUID randomization.

Shortlog with bot lockfile bumps omitted:

    Benjamin Gilbert (11):
          20live: log rootfs fetch errors
          40ignition-ostree: generalize rootfs naming to transposefs
          40ignition-ostree: rename variable
          40ignition-ostree: add helper function for querying filesystems
          40ignition-ostree: support saving/restoring boot partition
          40ignition-ostree: support saving/restoring ESP
          40ignition-ostree: copy BIOS-BOOT partition and boot sector
          40ignition-ostree: copy PReP partition
          99emergency-timeout: fix log display from failed units
          40ignition-ostree: drop obsolete comment
          40ignition-ostree: fix possible transposefs-restore race

    Dusty Mabe (4):
          Revert "overlay: 15fcos: add systemd unit to migrate to systemd-resolved"
          tests/manual: nettest: make inspecting disk image more dynamic
          tests/manual: add coreos-docs-net-testing.sh
          tests/kola/ignition: add ignition.systemd-unmasking test

    Jakub Čajka (1):
          bootable-rpm-ostree: move to s390utils-core to get rid of perl dependency on main

    Jonathan Lebon (2):
          40ignition-ostree: be verbose about what we're mounting
          40ignition-ostree: consistently echo msg before mounting

    Luca BRUNO (1):
          dracut/15coreos-network: enable initramfs networking on Azure

    Sohan Kunkerkar (1):
          overrides: fast-track Ignition 2.8.1

### CODE REVIEW

**Comment by cgwalters** [comment]
Currently CI in this repo is just a syntax check (working on fixing that); did you do any manual testing on this?

All the changes look sane though!
/approve

**Comment by bgilbert** [comment]
Nope, I was relying on CI.  I'll do a build.

**Comment by cgwalters** [comment]
Want to rebase?

**Comment by bgilbert** [comment]
Passes a local `--no-net` kola run.

**Pull request merged**
