### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Benjamin Gilbert (6):
      overlay/15fcos: upgrade bootloader on aarch64 at boot
      denylist: re-snooze tests using Butane experimental spec
      tests/kola: hard-disable tests using Butane experimental spec
      Revert "denylist: re-snooze tests using Butane experimental spec"
      tests/kola: stabilize Butane 1.5.0 spec
      Revert "tests/kola: hard-disable tests using Butane experimental spec"

Dusty Mabe (10):
      tests/kola: add ext.config.networking.nm-ifcfg-rh-plugin test
      denylist: drop ext.config.files.file-directory-permissions denial
      denylist: bump snooze for ext.config.kdump.crash on aarch64
      Revert "overlay/15fcos: upgrade bootloader on aarch64 at boot"
      manifests/shared-workarounds: drop multipathd-service-fix
      overrides: drop kernel-6.1.18-200.fc37 pin
      Remove the fedora-rawhide-nodebug-kernel repo from fedora-rawhide.repo
      tests/kola: add extended upgrade test
      denylist: expand kdump.crash denial to all streams
      overlay.d/20platform-chrony: additional skip of platform chrony config

Enrique Llorente (1):
      networking-tools: Add nmstate

gursewak1997 (1):
      kola: Add ignition.journald-log test
```

### CODE REVIEW

**Comment by jlebon** [comment]
Any reason to hold these back related to the 9.2 work?

/approve
/assign travier

**Review by jschintag — APPROVED** [review]
Latest update is only lockfile bump.
/lgtm

**Pull request merged**
