### PR TITLE
manifest: add ppc64le packages to detect dynamically attached devices

### PR DESCRIPTION
**Pull request by Prashanth684**
same as https://github.com/coreos/fedora-coreos-config/pull/296

### CODE REVIEW

**Comment by jlebon** [comment]
Is this missing the same change to presets as the FCOS one?

**Comment by cgwalters** [comment]
One option is to split the manifest bits for this into a separate include that can be shared between the two.  We're a bit overdue to try to extract something like a `fedora-coreos-core.yaml` or so.

But OK as is too.
/approve

**Comment by Prashanth684** [comment]
> Is this missing the same change to presets as the FCOS one?

so isn't  `overlay.d/05core/usr/lib/systemd/system-preset/40-coreos.preset` common for rhcos too? Unfortunately i don't have a power machine to test on now..but i was thinking that the preset file was common.

**Comment by jlebon** [comment]
> so isn't `overlay.d/05core/usr/lib/systemd/system-preset/40-coreos.preset` common for rhcos too?

Yes, you're right. Thanks!

/lgtm

**Pull request merged**
