### PR TITLE
NO-JIRA: make bootupd not arch specific

### PR DESCRIPTION
**Pull request by dustymabe**
It's available for all architectures now.

### CODE REVIEW

**Comment by travier** [comment]
/hold
We are indeed building 9.4 by default now but this will break our 9.2 (backup builds). It's unlikely that we'll need those now but just in case, let's hold a short while until we remove all 9.2 traces from here.

**Comment by dustymabe** [comment]
can we just tag in newer bootupd into 4.16 9.2 tags like we did for 4.15?

This is currently blocking OSBuild because we can't build images for ppc64le.

**Comment by travier** [comment]
/unhold
Let's not block osbuild work for that

**Pull request merged**
