### PR TITLE
OCPBUGS-3705: [release-4.9] bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by dustymabe**
```
$ git shortlog --no-merges 96217fd..6d912d4
Dusty Mabe (1):
          tests/kola/root-reprovision: add `reprovision` tag
```

### CODE REVIEW

**Comment by mike-nguyen** [comment]
/retitle OCPBUGS-3705: [release-4.9] bump fedora-coreos-config

**Comment by ashcrow** [comment]
The `build-test-qemu` is failing on:

> Cannot download Packages/t/tpm2-tss-2.3.2-3.el8.x86_64.rpm ([log reference](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_os/1062/pull-ci-openshift-os-release-4.9-build-test-qemu/1592591016676823040#1:build-log.txt%3A1188))

**Comment by ashcrow** [comment]
Looks like the network issue is over but now we're seeing `semodule: unrecognized option '--rebuild-if-modules-changed'`

**Comment by dustymabe** [comment]
> Looks like the network issue is over but now we're seeing `semodule: unrecognized option '--rebuild-if-modules-changed'`

This feels a bit like one of `rpm-ostree` or `selinux` has been updated in the package set is using an option that was outdated or is too new.

**Comment by jlebon** [comment]
So yes, https://github.com/coreos/rpm-ostree/pull/4122 breaks composing target systems that have old semanage without the switch. We could fix this, but the larger issue here is that it looks like Prow is using the latest cosa to build 4.9.

**Comment by dustymabe** [comment]
> the larger issue here is that it looks like Prow is using the latest cosa to build 4.9.

Can we override that test here then (especially considering we are only changing tags on tests)?

**Comment by jlebon** [comment]
Yeah, the change itself can't really break anything in the old pipeline.

/override ci/prow/build-test-qemu

**Comment by jlebon** [comment]
> We could fix this, but the larger issue here is that it looks like Prow is using the latest cosa to build 4.9.

I think https://github.com/openshift/release/pull/34089 fixes this.

**Pull request merged**
