### PR TITLE
extensions: use stream9 as builder because of s390x

### PR DESCRIPTION
**Pull request by jmarrero**
closes https://github.com/openshift/os/issues/986

### CODE REVIEW

**Comment by jschintag** [comment]
Thanks @cgwalters and @jmarrero for taking such a quick look at it.

**Comment by cgwalters** [comment]
CI doesn't cover this (although it could...that's another topic)
/override ci/prow/rhcos-86-build-test-qemu 
/override ci/prow/scos-9-build-test-qemu

**Pull request merged**
