### PR TITLE
[release-4.14] Bump fedora-coreos-config submodule

### PR DESCRIPTION
**Pull request by dustymabe**
```
$ git -C fedora-coreos-config shortlog --no-merges  46f7228..6021695

Colin Walters (1):
      transposefs: Only autosave-xfs for much larger filesystems

Dusty Mabe (1):
      overlay.d: add 30lvmdevices overlay
```

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
As an aside, the current flow requires all changes for 4.14 to be *triplicated* - merged to testing-devel, merged to rhcos-4.14 branch in f-c-c, then merged here; I think it'd make sense to eliminate the middleman and basically not use a git submodule as soon as we have a need to branch for releases.  Maybe instead of submodules at all we should use a [git subtree](https://www.atlassian.com/git/tutorials/git-subtree) flow.  Or, I guess just give up and package it all as an RPM and manage it that way.

**Comment by travier** [comment]
So it looks like it's already in there as we haven't branched 4.14 apparently: https://github.com/openshift/os/commits/release-4.14

**Comment by travier** [comment]
Excepted for the submodule bump which now points to the wrong commit :/

**Comment by travier** [comment]
Closing as we haven't branched 4.14 yet.
/close

**Comment by cgwalters** [comment]
> Closing as we haven't branched 4.14 yet.

Nice, thanks for catching that!

**Pull request closed without merging**
