### PR TITLE
NO-JIRA: extensions: drop extensions for el-only variants

### PR DESCRIPTION
**Pull request by jlebon**
The extensions container contains OCP-versioned packages, so it needs to
be built alongside (or more likely as a follow-up to) the node image.

So then it doesn't make sense to have extensions symlinks for the
el-only variants. Nuke those.

The diff here looks scarier than it is. It's mostly shuffling
files around so that some things that were previously symlinks are
now files. Essentially:

```
mv extensions-rhel-9.4.yaml extensions-ocp-rhel-9.4.yaml
mv extensions-rhel-9.6.yaml extensions-ocp-rhel-9.6.yaml
mv extensions-c9s.yaml extensions-okd-c9s.yaml
```

See also: https://issues.redhat.com/browse/COS-3017

### CODE REVIEW

**Comment by dustymabe** [comment]
> prep for dropping the 9.4 variants.

I assume you were alluding to this when you made the above statement but just making sure... this effectively changes `extensions-ocp-rhel-9.4.yaml` in the following way:

```diff
$ diff -ur extensions-ocp-rhel-9.4.yaml extensions-ocp-rhel-9.6.yaml
--- extensions-ocp-rhel-9.4.yaml        2024-12-05 16:15:05.147654375 -0500
+++ extensions-ocp-rhel-9.6.yaml        2024-12-05 16:15:05.147654375 -0500
@@ -9,7 +9,7 @@
       - x86_64
       - aarch64
     repos:
-      - rhel-9.4-server-ose-4.19
+      - rhel-9.6-server-ose-4.19
     packages:
       - crun-wasm
   # https://github.com/coreos/fedora-coreos-tracker/issues/1504
@@ -52,7 +52,7 @@
     architectures:
       - x86_64
     repos:
-      - rhel-9.4-nfv
+      - rhel-9.6-nfv
     packages:
       - kernel-rt-core
       - kernel-rt-kvm
@@ -69,7 +69,7 @@
       - x86_64
       - s390x
     repos:
-      - rhel-9.4-server-ose-4.19
+      - rhel-9.6-server-ose-4.19
     packages:
       - kata-containers
   # https://issues.redhat.com/browse/COS-2402
```

**Comment by jlebon** [comment]
Whoops, nice catch! I redid it and documented the commands I ran in the commit message.

**Review by dustymabe — APPROVED** [review]
/lgtm

**Comment by mike-nguyen** [comment]
/retitle NO-JIRA: extensions: drop extensions for el-only variants

**Pull request merged**
