### PR TITLE
Revert "overlay.d/05rhcos: add rhcos-upgrade-root-filesystem-container"

### PR DESCRIPTION
**Pull request by arithx**
This reverts commit 66d1df13cea80569e19d5f7c73632f58e13a288f.

This upgrade script cannot live in the real root (we need to perform different actions on other architectures; see #448). Revert for 4.7 and implement an initrd based option in 4.8.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
OK right...and we had kept `coreos-luks-open.service` because we needed it until *after* the reboot from the migration script we're deleting.

**Review by jlebon — APPROVED** [review]

**Comment by arithx** [comment]
> OK right...and we had kept `coreos-luks-open.service` because we needed it until _after_ the reboot from the migration script we're deleting.

Yup. It's been stripped down to just the unlocking / dm-linear mapping bits (see 2fba76ec51001e6402d62bb3df13fb484fce5130 for the detailed view) but it is still present.

**Comment by jlebon** [comment]
(Will shepherd this through together with https://github.com/openshift/os/pull/482.)

**Pull request merged**
