### PR TITLE
Dockerfile,Makefile: Use coreos-assembler

### PR DESCRIPTION
**Pull request by cgwalters**
Fixes the (we need a name for this I'll just make one up) "all-in-one-Dockerfile"
path again, which I broke when doing the -assembler switch to use yaml.

### CODE REVIEW

**Comment by smarterclayton** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_os/65/pull-ci-os-container-build/1000115800117350400/

**Comment by cgwalters** [comment]
Hm...is something in the prow job overriding the repos now?  I submitted https://github.com/openshift/os/pull/66

**Comment by smarterclayton** [comment]
That passed

**Comment by smarterclayton** [comment]
Yes, the prow job is now using the mirrors.  I'm going to do it in the job because i don't want the repo to be public.  See openshift/release#884

**Pull request merged**
