### PR TITLE
Add rhcos-rdgo rpmmd repo

### PR DESCRIPTION
**Pull request by cgwalters**
Otherwise we won't have ignition.

### CODE REVIEW

**Comment by jlebon** [comment]
We discussed hosting this publicly in S3, right? Working on that right now.

**Comment by cgwalters** [comment]
OK, though that's an orthogonal improvement right?

**Comment by jlebon** [comment]
https://github.com/openshift/os/pull/27

**Comment by ashcrow** [comment]
Since #27 merged is this safe to close?

**Pull request closed without merging**
