### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Benjamin Gilbert (2):
      workflows: add scheduled job to sync openshift/os submodule
      workflows: add stamp file in openshift/os to ensure we push rebases
```

### CODE REVIEW

**Comment by bgilbert** [comment]
#807 landed.  Lifting draft.

/ok-to-test

**Comment by cgwalters** [comment]
Looks like we're missing the equivalent of `@dependabot rebase`.

**Comment by bgilbert** [comment]
The job should be pushing a rebase, but isn't.  Workaround in https://github.com/coreos/fedora-coreos-config/pull/1776.

**Comment by bgilbert** [comment]
Closing to test https://github.com/openshift/release/pull/29289.

**Pull request closed without merging**
