### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by travier**
Bump fedora-coreos-config:

```
Benjamin Gilbert (2):
      16disable-zincati: add stub statoverride file
      overlay: add 06el9 overlay

Dusty Mabe (8):
      update fallback hostname handling; add test
      denylist: drop ext.config.extensions.* denial on rawhide
      denylist: drop the ext.config.toolbox rawhide denial
      denylist: snooze coreos.boot-mirror* tests
      manifests: drop explicit add of kernel-{core,modules}
      denylist: drop ext.config.binfmt.qemu on aarch64+rawhide
      Add fedora-rawhide-nodebug-kernel repo to fedora-rawhide.repo
      denylist: extend denial/snooze for coreos.boot-mirror* to rawhide

Jonathan Lebon (6):
      transposefs: mount filesystems read-only by default
      transposefs: factor out function to save filesystems
      transposefs: use stricter `find ... -exec ... {} +` variant
      35coreos-ignition: fix LUKS device paths
      35coreos-ignition: swap order of `luks` and `filesystems` keys
      Handle dm-verity-protected filesystems in s390x secex path

Luca BRUNO (6):
      manifests/passwd: update users details to resync with Fedora
      manifests/passwd: sort users by name
      manifests/passwd: update description for the 'root' user
      overlay/sysusers: add description comments to each fragment
      overlay/sysusers: add user entries
      overlay/sysusers: rename fragments containing both groups and users

Nikita Dubrovskii (1):
      s390x: fix secex workaround unit dependency

Timothée Ravier (1):
      manifest & tests: Test if a symlink is broken first

mohelt (2):
      manifests: Remove known broken symlinks
      tests: Look for broken symlinks
```

---

overlay: Add 06el9 overlay from FCOS

### CODE REVIEW

**Comment by travier** [comment]
Manually replace https://github.com/openshift/os/pull/957 to include the new overlay.

**Comment by cgwalters** [comment]
https://github.com/coreos/fedora-coreos-config/pull/1946

**Comment by travier** [comment]
Added a denylist entry for RHEL 8 only for this test.

**Review by HuijingHei — APPROVED** [review]
lgtm

**Pull request merged**
