### PR TITLE
[release-4.16] OCPBUGS-35748: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Dusty Mabe (1):
      .cci.jenkinsfile: disable testing on older RHCOS branch

Jonathan Lebon (1):
      overlays: drop `coreos-multipath-trigger.service`
```

### CODE REVIEW

**Review by c4rt0 — APPROVED** [review]
lgtm

**Comment by jlebon** [comment]
OK, this looks better now!

Will let

/assign @travier @mike-nguyen 

also review and add the required labels.

**Comment by jlebon** [comment]
We need to delete the SCOS tests on this branch. But for now

/override ci/prow/scos-9-build-test-qemu
/override ci/prow/scos-9-build-test-metal

**Comment by travier** [comment]
Skipping C9S tests is https://github.com/openshift/release/pull/53014

**Comment by travier** [comment]
/label staff-eng-approved
I don't think I can set that one (yet)

**Comment by jlebon** [comment]
Talked with @sdodson. He'll look at this on Monday once there's clarity on 4.16 timeline just in case we need to respin RHCOS before GA.

**Pull request merged**
