### PR TITLE
manifests: Prepare for variant support in COSA and add RHEL 9.0 & SCOS variants

### PR DESCRIPTION
**Pull request by travier**
This PR only adds the manifests and prepare the repo layout to match the upcoming COSA changes. This should be completely transparent for now but should make manual testing of RHCOS 9.0 & SCOS 9 easier.

---

manifests: Prepare for variant support in COSA

---

manifests: Add RHEL 9.0 variant

Only add the manifests and do not enable CI yet.

---

manifests: Add SCOS variant

Only add the manifests and do not enable CI yet.

### CODE REVIEW

**Comment by travier** [comment]
Replaces https://github.com/openshift/os/pull/854, https://github.com/openshift/os/pull/856 and https://github.com/openshift/os/pull/855

**Comment by cgwalters** [comment]
OK I got a local c9s build with two changes; first, we can use the `distribution-gpg-keys` we already have:

```
--- a/repos/c9s.repo
+++ b/repos/c9s.repo
@@ -4,7 +4,7 @@ baseurl=http://mirror.stream.centos.org/9-stream/BaseOS/$basearch/os
 gpgcheck=1
 repo_gpgcheck=0
 enabled=1
-gpgkey=file:///tmp/RPM-GPG-KEY-centosofficial
+gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official
 
 [appstream]
 name=CentOS Stream 9 - AppStream
@@ -12,7 +12,7 @@ baseurl=http://mirror.stream.centos.org/9-stream/AppStream/$basearch/os
 gpgcheck=1
 repo_gpgcheck=0
 enabled=1
-gpgkey=file:///tmp/RPM-GPG-KEY-centosofficial
+gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official
 
 [nfv]
 name=CentOS Stream 9 - NFV
@@ -20,7 +20,7 @@ baseurl=http://mirror.stream.centos.org/9-stream/NFV/$basearch/os
 gpgcheck=1
 repo_gpgcheck=0
 enabled=1
-gpgkey=file:///tmp/RPM-GPG-KEY-centosofficial
+gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official
 
 [rt]
 name=CentOS Stream 9 - RT
@@ -28,7 +28,7 @@ baseurl=http://mirror.stream.centos.org/9-stream/RT/$basearch/os
 gpgcheck=1
 repo_gpgcheck=0
 enabled=1
-gpgkey=file:///tmp/RPM-GPG-KEY-centosofficial
+gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official
 
 [openvswitch]
 name=CentOS Stream 9 OpenvSwitch
```

**Comment by cgwalters** [comment]
Second, I know there's debate about "where to build ocp packages" but we already do ship https://mirror.openshift.com/pub/openshift-v4/amd64/dependencies/rpms/4.11-el8-beta/

So via e.g.
```
cat > src/config/ocp.repo << EOF
[rhel-8-server-ose]
name=OCP rpms
baseurl=https://mirror.openshift.com/pub/openshift-v4/amd64/dependencies/rpms/4.11-el8-beta/
gpgcheck=0
enabled=1
EOF
$
```

We get that stuff; that one isn't gated on subscriptions so we can just include it by default.

**Pull request merged**
