### PR TITLE
[release-4.7] Target fedora-coreos-config branch rhcos-4.7 and bump

### PR DESCRIPTION
**Pull request by jlebon**
```
Jonathan Lebon (1):
      Revert "overlay/boot-mount-generator: Mount /boot read-only,nodev,nosuid"
```

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Looks like the CI did not check this one (not an issue here but something to keep in mind for later).

**Comment by travier** [comment]
Ping @cgwalters as this might need to be fixed from an another repo but I don't know which one.

**Comment by miabbott** [comment]
@travier I believe the job is defined here - https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/os/openshift-os-master-presubmits.yaml

Looking at the MCO repo as an example, I think we need another yaml for the 4.7 branch

e.g. https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7-presubmits.yaml

**Pull request merged**
