### PR TITLE
ci: enable ci tests as we have updated to RHEL 9.2 GA repos

### PR DESCRIPTION
**Pull request by HuijingHei**
See https://github.com/openshift/release/pull/39361

### CODE REVIEW

**Comment by travier** [comment]
/lgtm
We'll have to figure out the mirror issues now :/

**Comment by travier** [comment]
This reverts https://github.com/openshift/os/pull/1244 and will have to be backported to 4.13 too, where we need to disable C9S tests as well.

**Comment by HuijingHei** [comment]
A little wired about the mirror issues, retest again.

/retest-required

**Comment by travier** [comment]
This is really weird. Some packages fail to download but it's not the same ones one both jobs :/

**Comment by travier** [comment]
@HuijingHei Let's remove this test here as well: https://github.com/openshift/os/blob/master/ci/prow-entrypoint.sh#L133

**Comment by travier** [comment]
From one job:

```
Will download: 514 packages (848.5?MB)
Downloading from 'rhel-9.2-appstream'...done
error: Cannot download Packages/n/netavark-1.5.0-3.el9_2.x86_64.rpm: All mirrors were tried; Last error: Status code: 404 for http://base-4-13-rhel92.ocp.svc.cluster.local/rhel-9.2-appstream/Packages/n/nmstate-2.2.10-2.el9_2.x86_64.rpm (IP: 172.30.206.47)
error: failed to execute cmd-fetch: exit status 1
```

From the other:

```
Will download: 514 packages (848.5?MB)
Downloading from 'rhel-9.2-fast-datapath'...done
Downloading from 'rhel-9.2-appstream'...done
error: Cannot download Packages/n/nmstate-2.2.10-2.el9_2.x86_64.rpm: All mirrors were tried; Last error: Status code: 404 for http://base-4-13-rhel92.ocp.svc.cluster.local/rhel-9.2-appstream/Packages/g/git-core-2.39.3-1.el9_2.x86_64.rpm (IP: 172.30.206.47)
error: failed to execute cmd-fetch: exit status 1
```

**Pull request merged**
