### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Dusty Mabe (1):
      tests/kola: ignore newlines in default network behavior change test

Joseph Marrero (2):
      ignition-ostree: make sure we don't mount /sysroot before transposefs
      ignition-ostree: remove not needed Before= checks

Luke Yang (1):
      tests/kola: add space after ! in YAML architecture field

Michael Armijo (3):
      overrides: pin kernel-6.3.12-200.fc38
      Revert "denylist: snooze root-reprovision on testing-devel"
      denylist: bump snooze for ext.config.kdump.crash on aarch64

gursewak1997 (1):
      denylist: drop kdump.crash for ppc64le rawhide Closes: https://github.com/coreos/fedora-coreos-tracker/issues/1523
```

### CODE REVIEW

**Review by marmijo — APPROVED** [review]

**Review by jmarrero — APPROVED** [review]
/lgtm

**Comment by cgwalters** [comment]
/override ci/prow/scos-9-build-test-qemu 
Don't think it's related, we'll debug later

**Pull request merged**
