### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Dusty Mabe (5):
      overlay.d/05core: drop nmstate.service in preset file
      manifests/fedora-coreos-base: drop dracut nvmf workaround
      manifests: enable OSTree autopruning for ppc64le
      manifests: enable autoprune, re-add qcom dtbs on aarch64 in F39+
      overrides: fast-track ostree-2023.3-2.fc38

Huijing Hei (1):
      tests: add test `nvme-symlink` to verify GCP udev rules

Jonathan Lebon (1):
      tests/kola: upstream network-online login test from RHCOS
```

### CODE REVIEW

**Comment by jlebon** [comment]
I rebased this to pick up https://github.com/openshift/os/pull/1294 and included a commit to remove the test added there as per https://github.com/openshift/os/pull/1294#issuecomment-1564469367.

**Review by c4rt0 — APPROVED** [review]
LGTM

**Comment by c4rt0** [comment]
LGTM

**Comment by travier** [comment]
We'll have to re-add https://github.com/openshift/os/commit/20b15c638fdfad24ef6cb6921d58325e6c923106 to this one

**Comment by dustymabe** [comment]
> We'll have to re-add [20b15c6](https://github.com/openshift/os/commit/20b15c638fdfad24ef6cb6921d58325e6c923106) to this one

Done

**Review by jmarrero — APPROVED** [review]
/lgtm

**Pull request merged**
