### PR TITLE
overlay.d: delete `cosa-no-autolayer` knob file

### PR DESCRIPTION
**Pull request by jlebon**
It's the default behaviour now:
https://github.com/coreos/coreos-assembler/pull/2665

### CODE REVIEW

**Comment by jlebon** [comment]
This is the final step in https://github.com/coreos/coreos-assembler/pull/2641#issuecomment-1013285699.

**Comment by jlebon** [comment]
Let's wait a day or two on this to be nice because it's another cosa bump required on local developer machines and the stamp file doesn't really hurt there until then.

**Comment by jlebon** [comment]
/retest
/hold cancel

This should be good to go now!

**Review by sohankunkerkar — APPROVED** [review]

**Pull request merged**
