### PR TITLE
Switch to RHEL 9.0 by default

### PR DESCRIPTION
**Pull request by travier**
Done via:
```
$ cosa update-variant default rhel-coreos-9
```

Revert this commit to move RHCOS back to RHEL 8.6 by default.

### CODE REVIEW

**Comment by cgwalters** [comment]
Let's fold https://github.com/openshift/os/pull/951 into this...I don't think we should make the switch without tests running in Prow.

**Comment by travier** [comment]
We need to set the pipeline to explicitly build 8.6 by default for now before we can merge this one so I'd prefer to keep them separated and hold on this one.

**Comment by mrunalp** [comment]
@knobunc fyi

**Comment by travier** [comment]
@mrunalp Note that while we'll likely merge this at some point, this is not what will switch us to RHCOS 9 in OCP.

**Comment by travier** [comment]
We merged this (for 9.2) in https://github.com/openshift/os/pull/1189

**Pull request closed without merging**
