### PR TITLE
extensions: Drop kata-containers for now

### PR DESCRIPTION
**Pull request by cgwalters**
Until a new version is built.

### CODE REVIEW

**Comment by darkmuggle** [comment]
Before merging do we have an ETA on when https://github.com/openshift/os/issues/597 might be cleared by the Kata folks?

**Comment by cgwalters** [comment]
There's a build going now, if that succeeds let's close this.  

But it will also be useful to see if this PR hits any further CI issues past that, so let's keep it open.

**Comment by cgwalters** [comment]
```
 kola -p qemu-unpriv --output-dir tmp/kola run --qemu-nvme=true basic
2021-07-28T18:28:57Z kola: yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into string 
```

Ooh!  Yep a *new* CI failure.  I bet this is from https://github.com/openshift/os/pull/595/files

**Comment by fidencio** [comment]
> There's a build going now, if that succeeds let's close this.

The new build succeeded, by the way.  Thanks for the raising this to our attention and, as mentioned on #597, sorry for the breakage.

**Comment by miabbott** [comment]
> ```
>  kola -p qemu-unpriv --output-dir tmp/kola run --qemu-nvme=true basic
> 2021-07-28T18:28:57Z kola: yaml: unmarshal errors:
>   line 10: cannot unmarshal !!seq into string 
> ```
> 
> Ooh! Yep a _new_ CI failure. I bet this is from https://github.com/openshift/os/pull/595/files

That's frustrating; I strongly believe I tested that change locally with `cosa:latest`...but anyways #599

**Comment by cgwalters** [comment]
Yep `buildextend-extensions` works here now.

**Pull request closed without merging**
