### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Aashish Radhakrishnan (2):
      denylist: snooze ext.config.docker.basic on rawhide
      denylist: drop ext.config.kdump.crash test

Jonathan Lebon (4):
      05core/dracut: enable `iscsi` module
      kola/expected-contents: only check for `iscsi_ibft` on supported arches
      manifests: add crun-wasm.yaml
      Revert "coreos-teardown-initramfs: use NetworkManager to teardown networking"

Michael Armijo (1):
      overrides: fast-track glibc-2.37-10.fc38

Steven Presti (1):
      manifest: add bash-color-prompt for >= f39 fixes coreos/fedora-coreos-tracker#1567

Timothée Ravier (3):
      tests/kola/docker: Add a basic docker run test
      ci & tests: Switch to quay.io/fedora/fedora
      tests/kola/docker/basic: Only run on FCOS

gursewak1997 (5):
      upgrade/extended: Get latest release from update server This test fails when it is run during the time period between the stream build and the release. Updated the test to get the last_release from update server and check if there's an edge pointing to it.
      upgrade/extended: Fix last_release_index extraction method Initially, I was getting the last_release_index from the update json file itself under key org.fedoraproject.coreos.releases.age_index whereas we are using the actual index value of the versions as edge values in edges array
      denylist: extend snooze for coreos.ignition.ssh.key
      denylist: bump snooze for ext.config.kdump.crash on aarch64 This test is still failing.
      denylist: snooze kdump.crash for ppc64le in rawhide
```

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]

**Comment by jlebon** [comment]
This contains the fix for https://issues.redhat.com/browse/OCPBUGS-19811.

/approve
/lgtm

**Comment by travier** [comment]
```
--- FAIL: ext.config.shared.docker.basic (56.67s)
        cluster.go:162: Error: Unit kola-runext.service exited with code 127
```

Arg, I missed making this test FCOS only. Will make a PR.

**Comment by jlebon** [comment]
Forced a GHA rerun for this since it should now have everything we need. Thanks @travier for fixing the CI failure!

/approve
/lgtm

**Pull request merged**
