### PR TITLE
ci/build-test: Do a cosa build + test

### PR DESCRIPTION
**Pull request by cgwalters**
I think *finally* all the pieces are together for this.

Closes: https://github.com/openshift/os/issues/417

### CODE REVIEW

**Comment by cgwalters** [comment]
OK need https://github.com/openshift/release/pull/15149

**Comment by cgwalters** [comment]
oooo I'm logged in live on the pod here and it's working!!!1!

```
100  1388  100  1388    0     0  26188      0 --:--:-- --:--:-- --:--:-- 26188
+ cosa fetch
Config commit: v0.0.2-197-g547bf864daf3df23ad8ec0e02fabc889dbd80f12
Using manifest: /tmp/tmp.YJAxnHHo3I/src/config/manifest.yaml
Committing rhcos-config-overlay-01fcos: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/01fcos ... 4396a9c80dcb255f2a7260bedd99175976b9e1905b53b683af0531e8a0bdb089
Committing rhcos-config-overlay-02fcos-nouveau: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/02fcos-nouveau ... 0e8b1348eadaec949f811556c2b93260c39becc1a9154772315e11d3af8f2fc4
Committing rhcos-config-overlay-05rhcos: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/05rhcos ... 185548083116f652847c0c169beb218931216f0ad700e23420e916e904e9c7b3
Committing rhcos-config-overlay-15rhcos-tuned-bits: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/15rhcos-tuned-bits ... 132a9ae6b0c62337ccc87c831c5d4e754fc41a15e2f6f1804e9da1f6c66728de
Committing rhcos-config-overlay-20platform-chrony: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/20platform-chrony ... de1f04d79a09b32f2231ffd33d96107029ecfa022ebb03d1da07063368530afc
Committing rhcos-config-overlay-21dhcp-chrony: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/21dhcp-chrony ... b2b7ed911d135b5e73520e80638ec542ee01bb5238ad7c106dee283395e7642f
Committing rhcos-config-overlay-25rhcos-azure-udev-rules: /tmp/tmp.YJAxnHHo3I/src/config/overlay.d/25rhcos-azure-udev-rules ... 0bebf0ca5e847603d7f98f0af4acb5bc85224d3e4ff3c4162b9f53b16e41b9d3
Running: rpm-ostree compose tree --repo=/tmp/tmp.YJAxnHHo3I/tmp/repo --cachedir=/tmp/tmp.YJAxnHHo3I/cache --touch-if-changed /tmp/tmp.YJAxnHHo3I/tmp/treecompose.changed --unified-core /tmp/tmp.YJAxnHHo3I/tmp/override/coreos-assembler-override-manifest.yaml --download-only
info: Missing CAP_SYS_ADMIN; using virt
Formatting 'cache2.qcow2.tmp', fmt=qcow2 cluster_size=65536 compression_type=zlib size=10737418240 lazy_refcounts=off refcount_bits=16
```

**Review by ashcrow — APPROVED** [review]
Looks sane and this is great!

**Comment by cgwalters** [comment]
IT WORKED
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_os/490/pull-ci-openshift-os-master-unit/1352626743197831168/artifacts/build-logs/bin.log

**Comment by cgwalters** [comment]
So this will really just be the *start* - there's a whole lot we can do to build on this.  For example, we can "natively" build an oscontainer and push that for further promotion testing.  

We obviously really want
`/test e2e-aws`
here too etc.

**Comment by cgwalters** [comment]
Another thing I'd really like to do is add
```
/test e2e-aws-mco
```
that run's the MCO's test suite.

**Comment by cgwalters** [comment]
Also I need to figure out cosa gangplank more and try to use that here.

**Comment by jlebon** [comment]
Very cool! This closes a *major* gap.
/lgtm

Once CI is stronger here, we can also stop making this repo a submodule of the internal `redhat-coreos` repo. That'll require teaching the pipeline to decouple those.

> Also I need to figure out cosa gangplank more and try to use that here.

I think @LorbusChris and @ravanelli are also looking at Gangplank and hooking it up to this repo, so might want to coordinate with them as well.

**Pull request merged**
