### PR TITLE
OCPBUGS-3260: [release-4.11] bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by dustymabe**
```
$ git shortlog --no-merges a001715..60a42ac
Jonathan Lebon (1):
          tests/kola/root-reprovision: add `reprovision` tag
```

### CODE REVIEW

**Comment by mike-nguyen** [comment]
/retitle OCPBUGS-3260: [release-4.11] bump fedora-coreos-config

**Comment by HuijingHei** [comment]
retest

**Pull request merged**
