### PR TITLE
denylist: re-enable `bond-with-dhcp` and `bond-with-restart` for EL9

### PR DESCRIPTION
**Pull request by HuijingHei**
The change with scripts refer to https://github.com/coreos/coreos-assembler/pull/3079

### CODE REVIEW

**Comment by travier** [comment]
For the dnsmasq issue, should we update the tests instead of changing the default configuration or do we really want to update the default configuration?

**Comment by HuijingHei** [comment]
> For the dnsmasq issue, should we update the tests instead of changing the default configuration or do we really want to update the default configuration?

I will dig more about this, thanks for your suggestion.

**Comment by HuijingHei** [comment]
Change script https://github.com/coreos/coreos-assembler/pull/3079

**Comment by travier** [comment]
OK, it's an RHCOS only test thus why is wasn't failing previously on FCOS.

**Pull request merged**
