### PR TITLE
[rhel8.5 revert] Use RHEL8.6 repo for kata-containers

### PR DESCRIPTION
**Pull request by mike-nguyen**
Reverting back to RHEL 8.5 content caused extension building to fail
because the newer kata-container has a requirement on a qemu-kvm-core
version that is newer than the one in the rhel-8-advanced-virt repo.

Get the kata-containers dependencies from RHEL8.6 appstream.

See: https://github.com/openshift/os/issues/795

### CODE REVIEW

**Comment by miabbott** [comment]
Should be able to target `master` with this PR, right?

**Comment by miabbott** [comment]
I think you'll need to change the CI script to `curl` down the 8.6 repos and populate the `ocp.repo` file accordingly

**Comment by miabbott** [comment]
> I think you'll need to change the CI script to `curl` down the 8.6 repos and populate the `ocp.repo` file accordingly

I think I have a one-liner to do this, will push a commit to this PR

**Comment by mike-nguyen** [comment]
Second commit looks good to me

**Review by HuijingHei — APPROVED** [review]
LGTM

**Pull request merged**
