### PR TITLE
manifest: Pull skopeo and containers-common from OCP repo

### PR DESCRIPTION
**Pull request by cgwalters**
We need a new skopeo with `experimental-image-proxy` for
ostree containers.

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]
lgtm

**Comment by miabbott** [comment]
Which versions are required for this?  The plashets are currently holding `containers-common-1-13.rhaos4.10.el8` and `skopeo-1.5.2-0.rhaos4.10.el8.1`

**Comment by cgwalters** [comment]
1.5.2 is good (see also https://github.com/coreos/fedora-coreos-config/pull/1475 )

**Comment by cgwalters** [comment]
Uhh wait no we need 1.5.2, not 1.2.2

**Comment by cgwalters** [comment]
/hold cancel
OK I got confused between 4.10 and 4.11

**Review by saqibali-2k — APPROVED** [review]
/lgtm

**Pull request merged**
