### PR TITLE
extensions: Support variant for container image build

### PR DESCRIPTION
**Pull request by travier**
Look for the variant's manifest.yaml and extensions.yaml when set.

Fixes: https://github.com/openshift/os/issues/1080

### CODE REVIEW

**Comment by travier** [comment]
Will also do the BZ dance as I need to backport this to 4.12
/hold

**Review by cgwalters — APPROVED** [review]

**Comment by travier** [comment]
SCOS failures are tracked in https://github.com/openshift/os/issues/1089 https://github.com/openshift/os/issues/1090 https://github.com/openshift/os/issues/1091.

/override ci/prow/scos-9-build-test-qemu

**Pull request merged**
