### PR TITLE
overlay.d: Add 21dhcp-chrony to set default DHCP NTP settings 

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Preparation for https://github.com/coreos/fedora-coreos-config/pull/703
So the upstream patch for chrony change (https://src.fedoraproject.org/rpms/chrony/pull-request/3) is still not available in RHCOS, so we'd need to fork-lift [this change](https://github.com/coreos/fedora-coreos-config/pull/412) here to enable chrony-dhcp settings for propagating NTP servers information.

### CODE REVIEW

**Comment by dustymabe** [comment]
WDYT about adding [the test](https://github.com/coreos/fedora-coreos-config/blob/04a0322de1c194db677cd498a3c00c78230d6893/tests/kola/chrony/dhcp-propagation) here too?

**Comment by sohankunkerkar** [comment]
> WDYT about adding [the test](https://github.com/coreos/fedora-coreos-config/blob/04a0322de1c194db677cd498a3c00c78230d6893/tests/kola/chrony/dhcp-propagation) here too?

I think we're still keeping this test, right? https://github.com/openshift/os/blob/master/tests/kola/chrony/dhcp-propagation even after [this PR](https://github.com/coreos/fedora-coreos-config/pull/703)?

**Comment by dustymabe** [comment]
> > WDYT about adding [the test](https://github.com/coreos/fedora-coreos-config/blob/04a0322de1c194db677cd498a3c00c78230d6893/tests/kola/chrony/dhcp-propagation) here too?
> 
> I think we're still keeping this test, right? https://github.com/openshift/os/blob/master/tests/kola/chrony/dhcp-propagation even after [this PR](https://github.com/coreos/fedora-coreos-config/pull/703)?

Ahh, I missed it already exists. I guess let's just take this as a chance to diff that file with what is upstream in the FCOS configs now. Hopefully nothing has changed. If there's a diff let's see if it needs updating.

**Comment by sohankunkerkar** [comment]
Passes a local `exttest` kola run
```bash
$ cosa kola run -p qemu --qemu-image builds/47.83.202012170100-0/x86_64/rhcos-47.83.202012170100-0-qemu.x86_64.qcow2 'ext.config.chrony.*'
COREOS_ASSEMBLER_CONFIG_GIT=/home/skunkerk/fedora-coreos/src/github.com/openshift/os
+ podman run --rm -ti --security-opt label=disable --privileged --uidmap=1000:0:1 --uidmap=0:1:1000 --uidmap 1001:1001:64536 -v /home/skunkerk/fedora-coreos/rhcos:/srv/ --device /dev/kvm --device /dev/fuse --tmpfs /tmp -v /var/tmp:/var/tmp --name cosa -v /home/skunkerk/fedora-coreos/src/github.com/openshift/os:/srv/src/config/:ro quay.io/coreos-assembler/coreos-assembler:latest kola run -p qemu --qemu-image builds/47.83.202012170100-0/x86_64/rhcos-47.83.202012170100-0-qemu.x86_64.qcow2 'ext.config.chrony.*'
⚠️  Skipping kola test pattern "coreos.ignition.journald-log":
⚠️  https://github.com/coreos/coreos-assembler/issues/1173
kola --denylist-test coreos.ignition.journald-log --output-dir tmp/kola run -p qemu --qemu-image builds/47.83.202012170100-0/x86_64/rhcos-47.83.202012170100-0-qemu.x86_64.qcow2 ext.config.chrony.*
=== RUN   ext.config.chrony.dhcp-propagation
--- PASS: ext.config.chrony.dhcp-propagation (125.99s)
PASS, output in tmp/kola
+ rc=0
+ set +x
```

**Comment by dustymabe** [comment]
I didn't hand check every file, but assuming you just copied what was in FCOS.. LGTM

**Review by cgwalters — APPROVED** [review]
/lgtm

**Pull request merged**
