### PR TITLE
[release-4.17] NO-JIRA: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Jonathan Lebon (1):
      tests/kernel-replace: use `dnf repoquery` to get kernel version
```

### CODE REVIEW

**Review by aaradhak — APPROVED** [review]

**Review by marmijo — APPROVED** [review]
LGTM

**Comment by jlebon** [comment]
Needs https://github.com/coreos/fedora-coreos-config/pull/3108

**Comment by jlebon** [comment]
Well actually, this is only breaking on SCOS currently. And that CI shouldn't run on this branch:

https://github.com/openshift/release/pull/55836

For now, let's override it.

/override ci/prow/scos-9-build-test-qemu

We can get https://github.com/coreos/fedora-coreos-config/pull/3108 in once/if that bootc release lands in 9.4.

**Pull request merged**
