### PR TITLE
extensions: Enable SCOS extension builds with COSA

### PR DESCRIPTION
**Pull request by LorbusChris**
Not sure this'll work/

/cc @travier 
/cc @lmzuccarelli

### CODE REVIEW

**Comment by LorbusChris** [comment]
I wonder is the `FROM registry.ci.openshift.org/rhcos-devel/rhel-coreos:latest as os` getting replaced by COSA, or do we need to update that too for SCOS, too?

**Comment by travier** [comment]
No need to CC me on all PRs here. I actively watch this repo 🙂

**Comment by travier** [comment]
You can override some `FROM` in a container image with `--from` for podman builds but not sure that you can replace them all. You might need to make an entire copy of this Containerfile here for SCOS.

**Comment by LorbusChris** [comment]
My question is, when this is run via COSA, does COSA replace that FROM directive in any way? (i.e. is this run in the oscontainer that was just composed, or does COSA really pull that image, which I imagine would have to come from from a previous build?)

/cc @cgwalters

**Comment by cgwalters** [comment]
BTW @jmarrero wrote most of the code here so adding him

**Comment by jmarrero** [comment]
This passed here, I do a quick test in the next hr locally and approve it if it looks good.

**Comment by jmarrero** [comment]
@LorbusChris locally I get:

```
[1/3] STEP 6/6: RUN if [[ -z "$COSA" ]] ; then ci/get-ocp-repo.sh && variant="" ; else variant="-"+$(jq --raw-output '."coreos-assembler.config-variant"' 'src/config.json') ; fi     && rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}${variant}.yaml
jq: error: Could not open file src/config.json: No such file or directory
Error: error building at STEP "RUN if [[ -z "$COSA" ]] ; then ci/get-ocp-repo.sh && variant="" ; else variant="-"+$(jq --raw-output '."coreos-assembler.config-variant"' 'src/config.json') ; fi     && rpm-ostree compose extensions --rootfs=/ --output-dir=/usr/share/rpm-ostree/extensions/ {manifest,extensions}${variant}.yaml": error while running runtime: exit status 2
error: exit status 2
```

**Comment by jmarrero** [comment]
> It's not immediately clear to me why the `src` folder wouldn't be created when running COSA locally. I'll have to dig in a little more it seems.

It is there, you prep the directories it's just not finding the config.json file and I don't see it in either the fedora config or os repositories. Is this specific to scos? Is there a config.json in a SCOS repo somewhere?

**Comment by jmarrero** [comment]
Looks good locally now with cosa.

**Comment by jmarrero** [comment]
giving it another test now.

**Review by jmarrero — APPROVED** [review]
/lgtm

**Pull request merged**
