### PR TITLE
kola-denylist: disable crio.base tests for all arches

### PR DESCRIPTION
**Pull request by miabbott**
See: https://bugzilla.redhat.com/show_bug.cgi?id=1986239

### CODE REVIEW

**Comment by miabbott** [comment]
`error: fstatat(8f/eb7f5ee0571a28a2a7f999ad0be78d94b3b01b168ef2890f5e8b4435d53941.filez): Cannot allocate memory`

Cool, cool....

/retest

**Comment by miabbott** [comment]
BTW, this did correctly skip the `crio.base` test in my local tests

**Comment by miabbott** [comment]
Huh, this memory issue appears to be affecting all of our `openshift/os` Prow jobs - https://github.com/openshift/os/pull/593#issuecomment-886868659

**Comment by cgwalters** [comment]
/override ci/prow/build-test-qemu
This is just disabling a test, so should be OK.  I'm working on debugging CI in https://github.com/openshift/os/issues/594

**Pull request merged**
