### PR TITLE
OCPBUGS-4027: bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by c4rt0**
bump fedora-coreos-config

    ```
    $ git shortlog --no-merges 4664a23...0f8bbe

    Micah Abbott (1):
          manifests: move location of nvme-cli for sharing with RHCOS
    ```

See: https://issues.redhat.com/browse/COS-1870

### CODE REVIEW

**Review by ravanelli — COMMENTED** [review]
I think we should do the same approach done for https://github.com/coreos/fedora-coreos-config/pull/1436/commits/2dd6027deae6fd2ba90017782fecf33b87af4925 . The `nvmi-cli` is already present in FCOS https://github.com/coreos/fedora-coreos-config/blob/rhcos-4.10/manifest-lock.x86_64.json

You may cherry pick Micah's PR for it.

**Comment by jlebon** [comment]
> [0m[31merror: [0mCopying from build repo into target repo: Validating dirtree 17bac9ea23994a0b3d76303bdd5f0db9f8637b98cbe0e03306738899c9660ad3 (/usr/lib64/): fstatat(1c/42c1d77cbffa77c92d0d1fd0586855e6ae6462c9613ceea6c201c8d03e92a6.filez): Cannot allocate memory

I think this is 4.10 cosa not having all the 9p mitigation patches. Very soon, we should be folding e.g. `rhcos-4.10-new` back into `rhcos-4.10` which should help there. For now, you can do

/retest

**Comment by c4rt0** [comment]
> > �[0m�[31merror: �[0mCopying from build repo into target repo: Validating dirtree 17bac9ea23994a0b3d76303bdd5f0db9f8637b98cbe0e03306738899c9660ad3 (/usr/lib64/): fstatat(1c/42c1d77cbffa77c92d0d1fd0586855e6ae6462c9613ceea6c201c8d03e92a6.filez): Cannot allocate memory
> 
> I think this is 4.10 cosa not having all the 9p mitigation patches. Very soon, we should be folding e.g. `rhcos-4.10-new` back into `rhcos-4.10` which should help there. For now, you can do
> 
> /retest

Thank you :)

**Pull request merged**
