### PR TITLE
github: Add ShellCheck workflow

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/coreos/fedora-coreos-tracker/issues/1180

Added manually here (and not via the repo templates) as I don't think the bot has the right to make a pull request here (?)

Edit: Not sure the GitHub workflow run here. We'll likely have to adapt this one for Prow

### CODE REVIEW

**Comment by travier** [comment]
Needs https://github.com/coreos/fedora-coreos-config/pull/1966

**Comment by cgwalters** [comment]
> Edit: Not sure the GitHub workflow run here. We'll likely have to adapt this one for Prow

Currently Github Actions are disabled for the entire github.com/openshift organization.  But back then, actions by default had write access to the repository.  Nowadays, administrators can globally enforce read-only access, which basically obviates security concerns, so we could ask to have them turned on I think.

**Comment by travier** [comment]
Waiting on https://github.com/openshift/os/pull/1002

**Comment by travier** [comment]
I'd say let's start with this one as we already have a validation test and we can re-use the GitHub Action workflow later.

**Comment by cgwalters** [comment]
> sudo dnf install -y ShellCheck
> sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

Our default CI jobs in Prow run as non-root.  I think we should make another image for this that's pre-built; there may even be one.  Or ask to enable GH actions read-only.

**Comment by travier** [comment]
Always interesting what we can find using Google:
- https://github.com/openshift/installer/blob/master/hack/shellcheck.sh
- https://quay.io/repository/coreos/shellcheck-alpine
Looking for the source/sync job now :)

**Comment by cgwalters** [comment]
xref https://github.com/coreos/rpm-ostree/pull/4008 where a different team at RH has a custom Github Action for this

**Comment by travier** [comment]
Blocked on https://github.com/coreos/fedora-coreos-config/issues/2117 + f-c-c bump

**Review by mike-nguyen — APPROVED** [review]

**Comment by travier** [comment]
We ended up adding ShellCheck directly to the build root in https://github.com/coreos/fedora-coreos-config/pull/2119

**Pull request merged**
