### PR TITLE
[release-4.7] fedora-coreos-config: bump for in-place LUKS auto-growpart

### PR DESCRIPTION
**Pull request by jlebon**
I.e. https://github.com/coreos/fedora-coreos-config/pull/878 for
https://bugzilla.redhat.com/show_bug.cgi?id=1934174.

```
Jonathan Lebon (5):
      overlay: nuke obsolete coreos-growpart.service preset
      overlay: rename coreos-growpart to ignition-ostree-growfs
      overlay/growfs: rename variable
      overlay/growfs: fix in-place root reprovisioning detection
      overlay/growfs: support growing LUKS containers
```

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/fedora-coreos-config/pull/887

**Comment by cgwalters** [comment]
Hmm no CI on branches...OK pushed https://github.com/openshift/release/pull/16697

**Comment by cgwalters** [comment]
Well, at least we can see that
`--- PASS: ext.config.luks.ignition (78.15s)`

So I'm comfortable overriding the CI here for now.

**Pull request merged**
