### PR TITLE
cloud.ks: Add core user to some groups

### PR DESCRIPTION
**Pull request by jlebon**
See https://github.com/openshift/os/pull/109#issuecomment-397651647.

(Untested).

### CODE REVIEW

**Comment by jlebon** [comment]
/hold
Sanity checking...

**Comment by cgwalters** [comment]
Ah sorry, had missed the hold.

**Comment by cgwalters** [comment]
We likely need e.g.:

```
diff --git a/host.yaml b/host.yaml
index 5b290d7..9603ac5 100644
--- a/host.yaml
+++ b/host.yaml
@@ -20,6 +20,8 @@ mutate-os-release: "7"
 postprocess-script: "compose-post.sh"
 etc-group-members:
   - wheel
+  - systemd-journal
+  - adm
   - docker
 ignore-removed-users:
   - root
```

**Comment by jlebon** [comment]
OK, I've confirmed this works! Though it requires us to update the `coreos-assembler` container to use the latest rpm-ostree for https://github.com/projectatomic/rpm-ostree/pull/1417.

**Comment by ashcrow** [comment]
Since this is waiting for a merge and rebuild of another PR should this go back on hold?

**Comment by ashcrow** [comment]
The other PR merged. Is it OK to merge now?

**Comment by jlebon** [comment]
Hmm, let's leave it open until https://github.com/cgwalters/coreos-assembler/pull/5 is merged and the container rebuilt. If we merge this now, we'll be going from a `core` user without any groups to no `core` user at all (at least that's how my tests went locally before https://github.com/projectatomic/rpm-ostree/pull/1417 was merged).

**Comment by jlebon** [comment]
`coreos-assembler` was rebuilt with the fix, so this should be good to go now!
/hold cancel

**Pull request merged**
