### PR TITLE
NO-JIRA: c9s: Small fixes

### PR DESCRIPTION
**Pull request by travier**
c9s: Point image-c9s to image-rhel-9.4

---

c9s: Use RPMs from 9.4 RHAOS repo

---

Revert "c9s.repo: temporarily use mirrored repos"

This reverts commit 88e41a0fef0dbe8e0b2d103cadd37217c8cd0933.

### CODE REVIEW

**Comment by travier** [comment]
CI in https://github.com/openshift/os/pull/1498 keeps failing and I don't understand why so let's start with those smaller changes.

**Comment by travier** [comment]
```
```

**Comment by travier** [comment]
```
Importing rpm-md...done
rpm-md repo 'rhel-9.4-baseos'; generated: 2024-05-02T07:02:38Z solvables: 0
rpm-md repo 'rhel-9.4-appstream'; generated: 2024-05-02T07:16:36Z solvables: 0
```

**Comment by travier** [comment]
https://github.com/openshift/release/pull/51750

**Comment by jlebon** [comment]
Some overlap with #1502, but happy to rebase the latter!
/hold cancel
/lgtm

**Pull request merged**
