### PR TITLE
Jenkinsfile: New

### PR DESCRIPTION
**Pull request by cgwalters**
Just playing around with Pipeline.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Now failing https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_os/1/pull-ci-os-container-build/992583004360544256/build-log.txt because you're trying to access cdn.stage.redhat.com.

I'll add the ops mirror to the secrets injected into the namespace and pass it via an image builder mount for now.

**Comment by ashcrow** [comment]
I believe https://github.com/openshift/os/pull/5 supersedes this PR.

**Pull request closed without merging**
