### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by ravanelli**
```
Benjamin Gilbert (23):
      overrides: fast-track Afterburn 5.2.0-4
      workflows: fix copypaste error in step name
      ci/remove-graduated-overrides: rename and move to subcommand
      ci/overrides: rename function for clarity
      ci/overrides: move lockfile writing to a helper function
      ci/overrides: don't assume we're running in the root of the repo
      ci/overrides: use yaml.safe_load()
      ci/overrides: add commands to pin and fast-track packages
      ci/overrides: check for mismatched dist tags
      ci/overrides: require fast-track reason for non-CoreOS packages
      ci/overrides: add a query command to map a Bodhi update to SRPM NVRs
      workflows: add manual workflow to fast-track or pin packages
      README: document overrides.py and its GitHub workflow
      workflows/remove-graduated-overrides: clean up workflow display name
      workflows/remove-graduated-overrides: allow manual runs via Actions tab
      workflows/remove-graduated-overrides: improve PR message body
      ci/overrides: fail if we didn't fast-track/pin anything
      tests/kola/root-reprovision/swap-before-root: set allowConfigWarnings
      manifests/bootable-rpm-ostree: drop linux-firmware-whence
      ci/overrides: add helper lambda for detecting "noarch"
      ci/overrides: return info dict from get_binary_packages()
      ci/overrides: correctly add noarch overrides
      ci/overrides: support pin/fast-track on mechanical streams

Colin Walters (2):
      tests/skopeo: Verify `experimental-image-proxy` exists
      tests/default-network-behavior-change: Adapt to RHCOS 4.11

CoreOS Bot (26):
      lockfiles: drop graduated overrides 🎓
      lockfiles: bump to latest
      lockfiles: drop graduated overrides 🎓
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: drop graduated overrides 🎓
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      overrides: pin kernel-5.15.18-200.fc35
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: drop graduated overrides 🎓
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      overrides: fast-track rust-coreos-installer-0.13.1-1.fc35
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: drop graduated overrides 🎓

Dusty Mabe (20):
      overrides: fast-track kernel-5.15.17-200.fc35
      tests/extensions: bump timeout for the package test
      tests/extensions: limit to running on one platform
      denylist: extend snooze for all rawhide targeted tests
      tests/extensions: bump timeout for the module test
      tests/root-reprovision: bump timeout for reprovision tests to 15m
      manifests/bootable-rpm-ostree: explicitly add linux-firmware
      denylist: snooze the coreos.boot-mirror.luks test
      denylist: extend snoozes for rawhide
      denylist: extend snooze for ostree.hotfix on rawhide/aarch64
      denylist: snooze ext.config.chrony.dhcp-propagation in rawhide
      denylist: apply snoozes to the branched stream as well
      denylist: extend snoozes for rawhide, branched
      shared-workarounds: adjust multipath fix to apply to F37 too
      denylist: snooze ext.config.toolbox test in rawhide
      denylist: snooze the coreos.boot-mirror.luks test
      denylist: remove podman.base snooze
      denylist: extend snoozes for still failing tests
      tests/default-network-behavior-change: update for NM 1.36.0
      denylist: snooze the ext.config.firewall.iptables test on next*

Huijing Hei (1):
      denylist: enable coreos.boot-mirror.luks test

Jan Schintag (2):
      tests/kola: Skip grub specific parts on s390x in reboot test
      tests/kola: Skip incompatible tests on s390x

Jonathan Lebon (8):
      coreos-boot-edit: run `rdcore bind-boot`
      tests/extensions.package: don't try vim on rawhide
      35coreos-multipath: propagate config on first boot
      denylist: snooze `ext.config.extensions.module` for now
      overlay.d: add 35coreos-iptables
      tests: add iptables-nft test
      tests/manual: add iptables-nft upgrade tests
      kola-denylist: snooze multipath.day1 for a week

Marcio Xavier (1):
      skipping EFI on arch ppc64le and s390x

Micah Abbott (1):
      tests/k8s/systemd-env-read: search all lines of service logs

Nikita Dubrovskii (3):
      overlay.d: add udev rule for creating stable symlink to boot disk
      overlay: add coreos-unique-boot.service
      overlay: verify filesystem labeled 'boot' is unique after ignition

Timothée Ravier (2):
      tests: Rework 'find' calls with multiple file type filters
      tests: Add exclude lists for RHCOS

```

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by ravanelli** [comment]
Bump reason, Power CI is blocked due kola testing failing that were skipped/fixed in fcos.

**Comment by miabbott** [comment]
There's something up with the mirrored repos that I am trying to sort out with folks on Slack - https://coreos.slack.com/archives/CBN38N3MW/p1645627882391719

It's causing the CI job to fail

**Comment by ravanelli** [comment]
The test constantly failing is `non-exclusive-test-bucket-0`. There is an open issue for it: https://github.com/coreos/fedora-coreos-tracker/issues/1108

**Pull request merged**
