### PR TITLE
Bump fedora-coreos-config to latest

### PR DESCRIPTION
**Pull request by jlebon**
Mostly for https://github.com/coreos/fedora-coreos-config/pull/942 for
https://bugzilla.redhat.com/show_bug.cgi?id=1947490.

```
Colin Walters (6):
      buildroot: Add jq
      buildroot: Add attr
      buildroot: Also pull in python3-pyyaml
      buildroot: Add rsync
      buildroot: Blow out quay.io cache
      buildroot: Drop USER creation, add createrepo_c+ostree

Dusty Mabe (5):
      tests/manual: docsnettest: enhance dhcp server instructions
      tests/manual: docsnettest: align the dhcpvlan test
      tests/manual: remove bug workarounds from net tests
      35coreos-live/coreos-livepxe-rootfs: add in connectivity check before downloading
      tests/kola: handle possible rootless-systemd flake

Jonathan Lebon (16):
      overrides: move to an arch-independent lockfile
      overlay: propagate rootfs mountOptions to rootflags karg
      Move buildroot image here
      image.yaml: split out image-base.yaml
      buildroot: add dumb-init
      ci/buildroot: default to builder user
      ci/buildroot: set WORKDIR to /home/builder
      ci: use --parent-build
      ci: print human-readable RPM diff
      ci: error out if downgrade detected
      ci: use `cosa basearch` instead of hardcoding x86_64
      Move next-devel to cgroupsv2 for new nodes
      35coreos-network: enable initrd networking on azurestack
      tests/kola/var-mount: convert to Butane config
      tests/kola/var-mount: test mounting on reboot
      presets: enable clevis-luks-askpass.path

Kelvin Fan (2):
      overrides: Fast-track console-login-helper-messages-0.21.2.fc33
      12kdump: Remount /boot rw before `kdump.service`

Sinny Kumari (1):
      overrides: drop coreos-installer

Sohan Kunkerkar (2):
      overrides: fast-track coreos-installer 0.9.0
      overrides: fast-track afterburn release

Timothée Ravier (6):
      tests: Add basic toolbox functional testing
      manifests: Fix split to enable sharing with RHCOS
      manifests: Cosmetic changes
      manifests: Move stalld to shared 'system-configuration' manifest
      overrides: Fast-track podman 3.1.0-2
      tests: Add basic test for rpm-ostree countme

Vadim Rutkovsky (1):
      rootless-systemd: update packages before installing httpd
```

### CODE REVIEW

**Comment by jlebon** [comment]
Let's
/hold
this for now.

We should consider branching for 4.8 first before we do this.

**Comment by travier** [comment]
I made a bump for https://github.com/openshift/os/pull/512 too

**Comment by travier** [comment]
This one is fresher so maybe we can get it in first then the other

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
I think this one needs a rebase

**Pull request merged**
