### PR TITLE
kola-denylist: use string instead of list for tracker

### PR DESCRIPTION
**Pull request by miabbott**
I strongly believe that I tested the use of a list in the denylist as
part of #595, but evidence says otherwise.

### CODE REVIEW

**Comment by miabbott** [comment]
```[coreos-assembler]$ (cd src/config/ && git show HEAD)                                                                                                           
commit c4cef1eea5112b7197b554f4f9a70f29beb4224c (HEAD -> fix_denylist, miabbott/fix_denylist)
Author: Micah Abbott <miabbott@redhat.com>
Date:   Wed Jul 28 15:34:27 2021 -0400
                                                                               
    kola-denylist: use string instead of list for tracker
                       
    I strongly believe that I tested the use of a list in the denylist as
    part of #595, but evidence says otherwise.
                                                                               
diff --git a/kola-denylist.yaml b/kola-denylist.yaml
index 7beb6ac..34875e4 100644                   
--- a/kola-denylist.yaml               
+++ b/kola-denylist.yaml          
@@ -6,9 +6,7 @@       
   arches:                  
    - s390x            
 - pattern: crio.base           
-  tracker:                                                         
-    - https://github.com/kubernetes/kubernetes/issues/87325a
-    - https://bugzilla.redhat.com/show_bug.cgi?id=1986239
+  tracker: "https://github.com/kubernetes/kubernetes/issues/87325 && https://bugzilla.redhat.com/show_bug.cgi?id=1986239"
 # for s390x by-partlabel can't be used and even if that is avoided by using part-uuid, still depends on the cpi fix below
 - pattern: ext.config.var-mount
   tracker: https://github.com/ibm-s390-tools/s390-tools/pull/82
[coreos-assembler]$ jq . < /cosa/coreos-assembler-git.json 
{
  "date": "2021-07-28T14:30:42Z",
  "git": {
    "commit": "8d633557ccda112ceea30bc3462180256af09013",
    "origin": "git@github.com:coreos/coreos-assembler.git",
    "branch": "HEAD",
    "dirty": "false"
  },
  "file": {
    "checksum": "53bc7e3b05fb4d4698a9be84939bfe67d22468b66e6c86cdb1584f05e4ab55d4",
    "checksum_type": "sha256",
    "format": "tar.gz",
    "name": "coreos-assembler-git.tar.gz",
    "size": "39437099"
  }
}
[coreos-assembler]$ kola run 
⚠️  Skipping kola test pattern "crio.base":
  👉 https://github.com/kubernetes/kubernetes/issues/87325 && https://bugzilla.redhat.com/show_bug.cgi?id=1986239
⚠️  Skipping kola test pattern "coreos.ignition.journald-log":
  👉 https://github.com/coreos/coreos-assembler/issues/1173
=== RUN   coreos.tls.fetch-urls
=== RUN   ext.config.root-reprovision.raid1
=== RUN   coreos.boot-mirror.luks
=== RUN   rpmostree.status
=== RUN   coreos.ignition.failure
=== RUN   luks.sss.t1
=== RUN   rhcos.network.bond-with-dhcp
=== RUN   coreos.ignition.once
```

**Comment by cgwalters** [comment]
> I strongly believe that I tested the use of a list in the denylist as part of #595, but evidence says otherwise.

You mean you can't confirm...or deny it.

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
If this fails let's merge anyways but I want to see where we get from this run - at least kata should be in now.

**Comment by miabbott** [comment]
`error: Packages not found: bootupd, bootupd`

This is a comedy of errors

**Comment by cgwalters** [comment]
aos repo just got it, not sure if there's another process needed to sync
/retest

**Comment by miabbott** [comment]
> aos repo just got it, not sure if there's another process needed to sync
> /retest

Perhaps the sync from internal to the CI cluster is on a timer or what not

**Comment by jlebon** [comment]
If you somehow used cosa before https://github.com/coreos/coreos-assembler/pull/2296 when testing https://github.com/openshift/os/pull/595, that could explain why it worked. In Python, we just stringified it when printing. But we lost that when moving to stronger typing in golang.

Not a bad idea to officially support it though, even if just as a different e.g. `trackers` key.

**Pull request merged**
