### PR TITLE
tests/kdump: Use test definition from fedora-coreos-config

### PR DESCRIPTION
**Pull request by travier**
This also picks up the changes from there (keep it QEMU & x86_64 only for now).

### CODE REVIEW

**Comment by jlebon** [comment]
I've got a submodule bump going in https://github.com/openshift/os/pull/658. I can rebump it again to pick up the FCOS change. Just waiting for https://github.com/coreos/fedora-coreos-config/pull/1299 to get in as well. (Anyway, CI is currently broken.)

**Comment by travier** [comment]
This will need an update for https://github.com/coreos/fedora-coreos-config/pull/1338

**Comment by miabbott** [comment]
> This will need an update for [coreos/fedora-coreos-config#1338](https://github.com/coreos/fedora-coreos-config/pull/1338)

I think once https://github.com/coreos/fedora-coreos-config/pull/1322 lands, we can do more broad sharing of the FCOS tests and won't need to pick them individually

**Comment by miabbott** [comment]
This looks like it is superceded by #678

**Comment by travier** [comment]
Closing in favor of #678.
/close

**Pull request closed without merging**
