### PR TITLE
Update manifests and CI for 4.15

### PR DESCRIPTION
**Pull request by mike-nguyen**

### CODE REVIEW

**Comment by mike-nguyen** [comment]
Depends on https://github.com/openshift/os/pull/1331

**Comment by mike-nguyen** [comment]
/hold

Until https://github.com/openshift/os/pull/1331 is merged which requires the branch to open.

**Comment by mike-nguyen** [comment]
Waiting on the the rest of the steps after https://github.com/openshift/release/pull/41322 for the repo mirror to be up. This is causing the failures in CI.

**Comment by travier** [comment]
`/lgtm`

**Review by cgwalters — APPROVED** [review]

**Pull request merged**
