### PR TITLE
manifest/9.2: Ensure package come from RHEL by default

### PR DESCRIPTION
**Pull request by travier**
Make sure that we use RHEL (and not RHAOS) packages by default.

### CODE REVIEW

**Comment by travier** [comment]
```
ignition-2.15.0-1.el9.x86_64 (appstream)
```

This one is using the right version of Ingnition

**Comment by jlebon** [comment]
Seems sane, but is there a misconfiguration or bug here? Why aren't we already picking the highest NEVRA?

/approve

**Comment by cgwalters** [comment]
I'm confused, in https://github.com/openshift/os/issues/1187 we *are* using this version of Ignition and we are hitting that linked bug.

**Comment by travier** [comment]
Hum, indeed. That's weird

**Comment by travier** [comment]
OK so now this fails in 8.6 which does not have the new Ignition.

**Comment by travier** [comment]
Cleaning things in https://github.com/openshift/os/pull/1189

**Pull request merged**
