### PR TITLE
[release-4.14] OCPBUGS-35750: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Jonathan Lebon (1):
      overlays: drop `coreos-multipath-trigger.service`
```

### CODE REVIEW

**Review by jbtrystram — APPROVED** [review]
/lgtm

**Comment by jlebon** [comment]
/label backport-risk-assessed
/label cherry-pick-approved

@aaradhak is working on verifying https://issues.redhat.com//browse/OCPBUGS-35749, which should unblock this.

**Pull request merged**
