### PR TITLE
NO-JIRA: OWNERS: cleanup coreos group

### PR DESCRIPTION
**Pull request by jbtrystram**

### CODE REVIEW

**Review by marmijo — APPROVED** [review]
/lgtm

Thanks for cleaning up the members that are no longer part of the CoreOS group.

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/3835#issuecomment-2234334907

**Comment by travier** [comment]
You probably need to rename the file to OWNER_ALIAS or something. I vaguely remember us losing access to this repo in the past due to some similar changes. Can you take a look at the history?

**Comment by jbtrystram** [comment]
> You probably need to rename the file to OWNER_ALIAS or something. I vaguely remember us losing access to this repo in the past due to some similar changes. Can you take a look at the history?

https://github.com/openshift/os/commit/51c194d8ded69fc5d8c4d79a3f905a8cafad86a8

https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners_aliases
The documentation is not really clear as it if will work

**Pull request merged**
