### PR TITLE
Change repo names to match the RHCOS repo names

### PR DESCRIPTION
**Pull request by ravanelli**
- We are changing the repo names in order to improve our internal redhat-coreos repo, to use a single branch for the RHCOS versions.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Review by travier — APPROVED** [review]
/lgtm
/hold
Waiting on openshift/release changes

**Comment by jlebon** [comment]
This needs to update the repo name in the `extensions*.yaml` files.

**Comment by ravanelli** [comment]
@travier Any idea why `scos-9` tests are failing? 
Seems it is complaining about the changes done in: `awk '/rhel-9.0-server-ose-4.13/,/^$/' "src/config/tmp.repo" > "src/config/ocp90.repo"` 

Error:
````
rpm-ostree version: 2022.16
�[0m�[31merror: �[0mFailed to load /tmp/cosa/tmp/override/ocp90.repo: Key file does not start with a group
error: failed to execute cmd-fetch: exit status 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-11-23T00:37:55Z"}
```

**Comment by travier** [comment]
@ravanelli You can add a `cat ocp...repo` before/after the change to debug things in CI here.

**Comment by travier** [comment]
I understand now: As this PR had been pushed before the change in the repo in openshift/release, the step where we set the repos was likely cached in the build image.
Pushing a new commit triggered a full rebuild, thus this passes now.

**Comment by travier** [comment]
So you can remove the `cat`  and it should work.

**Comment by jlebon** [comment]
This passes CI now, great! We need to hold it until the internal MR is also ready to merge.

**Pull request merged**
