### PR TITLE
[release-4.14] OCPBUGS-17154: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by jlebon**
For https://github.com/coreos/fedora-coreos-config/pull/2660 for
https://issues.redhat.com/browse/OCPBUGS-17154.

```
Jonathan Lebon (1):
      Revert "coreos-teardown-initramfs: use NetworkManager to teardown networking"
```

### CODE REVIEW

**Comment by jlebon** [comment]
I'm not sure why the diff is larger than expected.

Hmm, it looks like the current submodule commit of f-c-c in the release-4.14 branch isn't actually what was in the 4.14 branch right before https://github.com/coreos/fedora-coreos-config/pull/2660 merged.

I think things might've gotten messed up during 4.14 branching somehow. But anyway, I think we do also want the other stuff in here?

**Comment by dustymabe** [comment]
I'm pretty sure things like adding LVM devices was already done i.e. in https://github.com/openshift/os/pull/1345#issuecomment-1699235342 and then verified by QA. 

Things certainly got messed up if we regressed and those "fixes" got pulled out of 4.14.

**Comment by jlebon** [comment]
/hold

Until we figure out what's going on here.

**Comment by jlebon** [comment]
Debugged this with @dustymabe. The f-c-c submodule on this branch was never following the rhcos-4.14 branch of f-c-c. We did the following:
- forced-pushed to the rhcos-4.14 branch of the f-c-c repo the exact commit that the release-4.14 branch was sitting on
- cherry-picked again my backport of https://github.com/coreos/fedora-coreos-config/pull/2660 on top
- verified that no commit which were thought to be backported in the rhcos-4.14 (but really would've never taken place) were all already in the ref

/hold cancel

**Comment by jlebon** [comment]
> * expected [Jira Issue OCPBUGS-17154](https://issues.redhat.com//browse/OCPBUGS-17154) to depend on a bug targeting a version in 4.15.0 and in one of the following states: MODIFIED, ON_QA, VERIFIED, but no dependents were found

Hmm, this is already in 4.15 as part of https://github.com/openshift/os/pull/1371. Can we just override this check or do we need to make a Jira ticket after the fact to satisfy it?

**Comment by jlebon** [comment]
Actually, let's hold this until we determine whether we want this in GA or as an early z update.

/hold

Discussions about that in https://issues.redhat.com/browse/OCPBUGS-17154.

**Comment by cgwalters** [comment]
> /hold

I moved to draft because it's a stricter check actually.

**Comment by HuijingHei** [comment]
Also probably fix https://issues.redhat.com/browse/OCPBUGS-16724, check `c4.2xlarge` nodes failed to start with the same error:
`Error: failed to set networking: Timeout was reached`

**Comment by jlebon** [comment]
@sdodson mentioned he's good with this if we are.
I'm +1 on doing this. Marked as ready for review to get CI going again.

@cgwalters If you agree, can you drop the `hold` label?

/assign @cgwalters

**Pull request merged**
