### PR TITLE
[release-4.12] NO-JIRA: extensions/Dockerfile: bump builder to f40

### PR DESCRIPTION
**Pull request by sdodson**
Backports #1585

### CODE REVIEW

**Review by aaradhak — APPROVED** [review]
/lgtm

**Review by marmijo — APPROVED** [review]
Not against this, but https://github.com/openshift/os/pull/1583 will be backported this far back and it will set the builder as `fedora:latest`

**Comment by marmijo** [comment]
/retitle [release-4.12] NO-JIRA: extensions/Dockerfile: bump builder to f40

**Comment by sdodson** [comment]
Yeah I just saw that but then figured this brings these branches inline with others and I think that'll at least make the eventual cherry-picks clean.

**Comment by marmijo** [comment]
Works for me! I don't remember what the original reasoning was behind not backporting it this far sooner. I know we experienced an issue with `fedora:38` content and this branch _was_ working fine.

**Pull request merged**
