### PR TITLE
ci/prow-entrypoint: Ensure we have a qemu image for followup builds

### PR DESCRIPTION
**Pull request by cgwalters**
This should fix https://github.com/coreos/coreos-assembler/pull/2919#issuecomment-1180824612

Fixes: c6e7dd9f99cfc9fe90ec87e041943743ab150cd6

### CODE REVIEW

**Comment by travier** [comment]
Note that nothing here tests this change thus why I did the hack in #890

**Comment by travier** [comment]
/close
Closing in favor of https://github.com/openshift/os/pull/891 until we test things more.

**Comment by cgwalters** [comment]
okay, but wouldn't you say this change is still obviously correct?

**Pull request closed without merging**
