### PR TITLE
c9s.repo: Use okd-4.17 yum repo

### PR DESCRIPTION
**Pull request by LorbusChris**
This is required for outside-of-Prow SCOS composes

### CODE REVIEW

**Comment by jlebon** [comment]
/approve
But CI is hitting:

```
 error: Installing packages: Updating rpm-md repo 'c9s-sig-cloud-okd': cannot update repo 'c9s-sig-cloud-okd': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://mirror.stream.centos.org/SIGs/9-stream/cloud/x86_64/okd-4.17/repodata/repomd.xml (IP: 13.226.52.102) 
```

**Review by jbtrystram — APPROVED** [review]
/lgtm
/approve

**Comment by jlebon** [comment]
I think this is obsolete now.

**Pull request closed without merging**
