### PR TITLE
[release-4.7] Bug 1941760: fedora-coreos-config: bump for lsblk workaround and prjquota

### PR DESCRIPTION
**Pull request by jlebon**
I.e. https://github.com/coreos/fedora-coreos-config/pull/900 (for
https://bugzilla.redhat.com/show_bug.cgi?id=1934863) and
https://github.com/coreos/fedora-coreos-config/pull/903 (for
https://bugzilla.redhat.com/show_bug.cgi?id=1940966).

```
Jonathan Lebon (5):
      overlay: don't restamp rootfs UUID if reprovisioning
      overlay/growfs: handle broken lsblk in el8
      tests/misc-ro: check for prjquota
      tests/root-reprovision: use `ok` and `fatal` helpers
      overlay: always use prjquota for XFS rootfs
```

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/fedora-coreos-config/pull/905

**Comment by jlebon** [comment]
(The SHA used will changed once that f-c-c PR is actually merged, so this will need to be updated. But the shortlog is the same)

**Comment by miabbott** [comment]
Just going to pick one BZ to make the bot happy

/retitle Bug 1934863: fedora-coreos-config: bump for lsblk workaround and prjquota

**Comment by miabbott** [comment]
CI could use this fix - https://github.com/openshift/os/pull/522

**Comment by miabbott** [comment]
@mike-nguyen is going to verify 1934174 today and if that is green, we should be able to merge this

**Comment by miabbott** [comment]
/retitle [release-4.7] Bug 1941760: fedora-coreos-config: bump for lsblk workaround and prjquota

**Pull request merged**
