### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Benjamin Gilbert (2):
      16disable-zincati: add stub statoverride file
      overlay: add 06el9 overlay

Colin Walters (1):
      tests/content-origins: Verify expected vendor for all RPM packages

Dusty Mabe (12):
      update fallback hostname handling; add test
      denylist: drop ext.config.extensions.* denial on rawhide
      denylist: drop the ext.config.toolbox rawhide denial
      denylist: snooze coreos.boot-mirror* tests
      manifests: drop explicit add of kernel-{core,modules}
      denylist: drop ext.config.binfmt.qemu on aarch64+rawhide
      Add fedora-rawhide-nodebug-kernel repo to fedora-rawhide.repo
      denylist: extend denial/snooze for coreos.boot-mirror* to rawhide
      Make fedora-rawhide-nodebug-kernel repo gpgcheck=0
      denylist: extend denials to `branched` stream, set snooze
      manifests/fedora-coreos: fix verbosity on postprocess script
      denylist: also deny #1215 issues against rawhide

Jonathan Lebon (6):
      transposefs: mount filesystems read-only by default
      transposefs: factor out function to save filesystems
      transposefs: use stricter `find ... -exec ... {} +` variant
      35coreos-ignition: fix LUKS device paths
      35coreos-ignition: swap order of `luks` and `filesystems` keys
      Handle dm-verity-protected filesystems in s390x secex path

Luca BRUNO (6):
      manifests/passwd: update users details to resync with Fedora
      manifests/passwd: sort users by name
      manifests/passwd: update description for the 'root' user
      overlay/sysusers: add description comments to each fragment
      overlay/sysusers: add user entries
      overlay/sysusers: rename fragments containing both groups and users

Nikita Dubrovskii (1):
      s390x: fix secex workaround unit dependency

Timothée Ravier (3):
      manifest & tests: Test if a symlink is broken first
      tests/validate-symlinks: QEMU & FCOS only
      README: Update test template

mohelt (2):
      manifests: Remove known broken symlinks
      tests: Look for broken symlinks
```

### CODE REVIEW

**Comment by jlebon** [comment]
/cc @nikita-dubrovskii Note this PR contains https://github.com/coreos/fedora-coreos-config/pull/1922.

The 8.6 CI test is failing on the newly added symlink test. /cc @mohelt 

The other ones seem to be failing on:

> error: Copying ostree layers from target repo into build repo: Failed to pull-local overlay/06el9: Refspec 'overlay/06el9' not found 

Which I'm not sure where that's coming from. We don't have that directory in `overlay.d` nor that ref in the manifests. @travier, possibly related to recent changes?

**Comment by travier** [comment]
Thanks, will take a look

**Comment by travier** [comment]
Replaced by https://github.com/openshift/os/pull/965

**Pull request closed without merging**
