### PR TITLE
cloud: add in 'core' user for now

### PR DESCRIPTION
**Pull request by dustymabe**
workaround for https://github.com/openshift/os/issues/96

### CODE REVIEW

**Comment by dustymabe** [comment]
i'm testing this now - will report back

**Comment by arithx** [comment]
I have a WIP commit for mantle which will automatically inject the rules into an AWS machine's Ignition config. I've done some limited testing so far but it is working atm: https://github.com/arithx/mantle/commit/cddefc147eaaab0c1e0738c9227c2da6dd61a6ec

**Comment by dustymabe** [comment]
so that just injects it in the ignition config when someone uses kola?

**Comment by dustymabe** [comment]
testing worked :100:

**Comment by arithx** [comment]
@dustymabe : Yeah, when the distribution is set to `rhcos` and it's running on AWS it injects into the Ignition config to create a file (the call itself takes `filesystem, path, contents string`).

**Comment by arithx** [comment]
If we're going to use this can we also add the `core` user to the `wheel`, `adm`, & `systemd-journal` groups?

**Comment by cgwalters** [comment]
I still feel like doing this in Ignition defaults will work best, but I have no problem doing this short term hack out of pragmatism.

**Pull request merged**
