### PR TITLE
OCPBUGS-42649: [release-4.16] Bump fedora-coreos-config to include 07fix-selinux-labels overlay

### PR DESCRIPTION
**Pull request by dustymabe**
Essentially a backport of https://github.com/coreos/fedora-coreos-config/pull/3150

### CODE REVIEW

**Review by jbtrystram — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
Let's hold on this one a little bit until we get full cluster / CI feedback (or lack of feedback) from https://github.com/openshift/os/pull/1626.

**Pull request merged**
