### PR TITLE
[release-4.16] c9s.repo: Use okd-4.16 yum repo

### PR DESCRIPTION
**Pull request by LorbusChris**
This is required for outside-of-Prow SCOS composes

### CODE REVIEW

**Comment by jlebon** [comment]
/retest
/approve
/lgtm
/label backport-risk-assessed

Do you have a Jira ticket already for this? If yes, might as well use it. If not, I'm OK to override it.

**Comment by travier** [comment]
Ideally we don't do backports for C9S. Can't this be fixed somewhere else in the pipeline?

**Comment by travier** [comment]
We also need to remove the C9S jobs for this branch.

**Comment by travier** [comment]
https://github.com/openshift/release/pull/53014

**Comment by travier** [comment]
/hold
As I said, we don't want to maintain C9S in branches. SCOS builds should only ever happen from the master branch.

**Comment by jlebon** [comment]
Let's close this based on discussions in https://github.com/openshift/release/pull/53014.

/close

**Pull request closed without merging**
