### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Colin Walters (1):
      overlay: Omit many more dracut modules explicitly

Dusty Mabe (4):
      manifests/user-experience: explicitly add file RPM
      tests: enable kdump.crash test for rawhide on s390x
      denylist: use more appropriate link for ppc64le kdump.crash denial
      denylist: extend snooze for ext.config.binfmt.qemu on rawhide/aarch64

Jonathan Lebon (4):
      overlay: omit bluetooth dracut module
      overlay: disable dracut stripping
      overlay: rename dracut.conf.d dropins
      40ignition-ostree: fix minor secex-related nits

Nikita Dubrovskii (2):
      s390x: reencrypt boot- and rootfs if SecureExecution is enabled
      s390x: workaround broken 'coreos-boot-disk' in 01-secex.ign config for RHCOS

Saqib Ali (1):
      35coreos-ignition: verify grub password directives
```

### CODE REVIEW

**Review by sohankunkerkar — APPROVED** [review]

**Comment by travier** [comment]
Let's get this one merged to try the fix from https://github.com/openshift/os/issues/908

**Pull request merged**
