### PR TITLE
ci: Skip Secure Boot tests for SCOS

### PR DESCRIPTION
**Pull request by travier**
Depends on https://github.com/coreos/coreos-assembler/pull/3145

### CODE REVIEW

**Comment by travier** [comment]
We need this one again now: https://github.com/openshift/os/pull/1049

**Comment by travier** [comment]
Note that https://bugzilla.redhat.com/show_bug.cgi?id=2138019 is not strictly fixed until we have a new kernel build.

**Comment by HuijingHei** [comment]
The failed cases are tracked by https://github.com/coreos/fedora-coreos-tracker/issues/1338

**Comment by travier** [comment]
Tracked in https://github.com/openshift/os/issues/1057

**Comment by travier** [comment]
Looks like we don't have an immediate Secure Boot issue anymore so will close this one.

**Pull request closed without merging**
