### PR TITLE
denylist: Add `ext.config.shared.multipath.multipathd-service-fix`

### PR DESCRIPTION
**Pull request by cgwalters**
See https://github.com/openshift/os/issues/1213

### CODE REVIEW

**Comment by cgwalters** [comment]
Denylist updates don't need CI
/override ci/prow/rhcos-92-build-test-metal
/override ci/prow/rhcos-92-build-test-qemu
/override ci/prow/scos-9-build-test-metal
/override ci/prow/scos-9-build-test-qemu

**Review by jmarrero — APPROVED** [review]
/lgtm

**Comment by cgwalters** [comment]
Denylist updates don't need CI
/override ci/prow/rhcos-92-build-test-metal
/override ci/prow/rhcos-92-build-test-qemu
/override ci/prow/scos-9-build-test-metal
/override ci/prow/scos-9-build-test-qemu

**Pull request merged**
