### PR TITLE
4.13 9.2

### PR DESCRIPTION
**Pull request by cgwalters**
This is a manual backport of https://github.com/openshift/os/pull/1204 
(Because that one got entangled with the 4.14 branching)

---

manifest/9.2: Ensure package come from RHEL by default

Make sure that we use RHEL (and not RHAOS) packages by default.

(cherry picked from commit 49f9824db2b6f929567d2d41cea6c97df766cf37)

---

overlay: Remove unused 25rhcos-azure-udev-rules

Not needed (and not actually used right now) in RHEL 8.6+ anymore.

(cherry picked from commit 5d5d0c583023a2cd9c301f2bad810098a9e8e565)

---

denylist: Skip ext.config.shared.ignition.resource.remote

See #1190

(cherry picked from commit d47155ab9aea4ad9a75e49189928482e504892b3)

---

s390x/kola-denylist: Re-enable working tests

fips.enable* is working on newest s390x. Remove the test from denylist.
For more details see #546

coreos.ignition.mount.* is fixed with gdisk-1.0.3-9.el8. Remove the test from
denylist.

ext.config.shared.ignition.stable-boot is fixed in RHEL 9. Only disable for
RHEL 8 builds.

Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
(cherry picked from commit 36729d18411c5e9ef3d21effa7896ee84f1518b9)

---

gitmodules: track rhcos-4.13 branch

Start tracing the rhcos-4.13 branch of fedora-coreos-config as a
part of branching for 4.13.

---

bump f-c-c submodule to track rhcos-4.13 branch

```
git shortlog --no-merges d170f19..f00040e1616ef244dfe622cad50b876d8087039e

Adam Piasecki (1):
      tests/kola/selinux/enforcing: Enhance SELinux mode test

Adam0Brien (1):
      F38 Changes: Kola test for shorter shutdown timer

CoreOS Bot (6):
      lockfiles: bump to latest
      lockfiles: bump to latest
      lockfiles: drop graduated overrides 🎓
      Sync repo templates ⚙
      lockfiles: bump to latest
      lockfiles: bump to latest

Dusty Mabe (4):
      tests/kola: add version comparison functions to commonlib.sh
      tests/kola: mark systemd.default-unit-timeouts as platform-independent
      tests/kola: break up long line in systemd.default-unit-timeouts
      denylist: bump snooze for files.file-directory-permissions

Huijing Hei (1):
      transposefs: add new workaround using try in loop

Jonathan Lebon (1):
      ci: update for new kolaTestIso()

gursewak1997 (2):
      Move chrony config from generator to systemd service
      platform-chrony: Make /run/coreos dir so we can create platform-chrony.conf
```

---

denylist: All ignition.resource.remote

Maintaining this test just requires way too much intricate
stuff to be chained together.

---

Merge pull request #1198 from travier/4.13-backports

[4.13] Backports from 4.14
---

Revert "manifest/9.2: Ensure package come from RHEL by default"

We already have to use coreos-installer from the RHAOS repo and it's
likely that we will have to do it again in the future for 4.14.

Remove this to avoid having to make a PR for each package.

This reverts commit 49f9824db2b6f929567d2d41cea6c97df766cf37.

(cherry picked from commit e346f8a350269e3966db9ade9df694e971cd3dfe)

---

manifest/9.2: Keep legacy coreos/toolbox

Unfortuantely, we're not yet ready to move to the new containers/toolbox
workflow. We'll attempt that for a future release.

See: https://issues.redhat.com/browse/OCPBUGS-8009
Partially reverts: https://github.com/openshift/os/commit/65776fa6e94fc25d73fd32a26f38547d55f61d44

(cherry picked from commit 3eb4abbaf2f892eb35a9c309b2ecd09b60c3d0fe)

---

manifests: Merge common-el9.yaml into common.yaml

(cherry picked from commit aa7f640cec3b879385db5bd86e8fa6188b28b396)

---

manifests/9.2: Use RHEL 9.2 repos

(cherry picked from commit 54daebb8e83ff4ecaaf9c6fa51f470f80a7ace0e)

---

manifest/c9s: Disable all repos by default

(cherry picked from commit ab22deeed0c02ab1b592daf80c2d01d747429fa3)

---

manifests: Remove RHEL 8 manifests

(cherry picked from commit be10693dcba52edfdce745ca735712c7796fd979)

---

manifests: Remove RHEL 9.0 manifests

(cherry picked from commit 27cd97c3710459414843ae2fd23ae039681dcdee)

---

manifest: Back to rhel toolbox

Since we don't have a legacy toolbox build in OCP channels yet.

(cherry picked from commit cdeb2523df43add1b7713c109c2273d8aa7cc6d0)

---

rhel-9.2: Fix two more references to 9.0

With this things build for me.

(cherry picked from commit fa8eef443fe124562680b8d333e23a9f629750ff)

---

More 90 -> 92 adjustments

(cherry picked from commit ee850172ff534635fb8c4fa3685ca1cc2beab067)

---

### CODE REVIEW

**Review by jmarrero — APPROVED** [review]

**Comment by cgwalters** [comment]
I was sanity checking this by doing

```
$ git diff origin/master..
diff --git a/.gitmodules b/.gitmodules
index 4af41576..7fbb1b7e 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,4 +1,4 @@
 [submodule "fedora-coreos-config"]
 	path = fedora-coreos-config
 	url = https://github.com/coreos/fedora-coreos-config
-	branch = testing-devel
+	branch = rhcos-4.13
diff --git a/ci/prow-entrypoint.sh b/ci/prow-entrypoint.sh
index 22e19283..ced382e6 100755
--- a/ci/prow-entrypoint.sh
+++ b/ci/prow-entrypoint.sh
@@ -73,9 +73,9 @@ prepare_repos() {
     # Figure out which version we're building
     rhelver=$(rpm-ostree compose tree --print-only "${manifest}" | jq -r '.["automatic-version-prefix"]' | cut -f2 -d.)
 
-    # Temporary workaround until we publish builds in the default path
-    if [[ "${rhelver}" == "92" ]]; then
-        prev_build_url="${REDIRECTOR_URL}/rhcos-${ocpver}-9.2/"
+    # Temporary workaround until we publish builds for other versions
+    if [[ "${rhelver}" == "86" ]]; then
+        prev_build_url="${REDIRECTOR_URL}/rhcos-${ocpver}/"
         # Fetch the previous build
         cosa buildfetch --url="${prev_build_url}"
     fi
@@ -84,16 +84,15 @@ prepare_repos() {
     case "${rhelver}" in
         92)
             curl --fail -L "http://base-${ocpver_mut}-rhel${rhelver}.ocp.svc.cluster.local" -o "src/config/ocp.repo"
-            # Work around podman not being built in 4.14
-            curl --fail -L "http://base-4-13-rhel${rhelver}.ocp.svc.cluster.local" -o "src/config/ocp-prev.repo"
-            cat src/config/ocp{,-prev}.repo
+            cat src/config/ocp.repo
             ;;
         *)
             # Assume C9S/SCOS if the version does not match known values for RHEL
             # Temporary workaround until we have all packages for SCOS
             curl --fail -L "http://base-${ocpver_mut}-rhel92.ocp.svc.cluster.local" -o "src/config/tmp.repo"
-            awk '/rhel-9.2-server-ose-4.14/,/^$/' "src/config/tmp.repo" > "src/config/ocp90.repo"
-            cat src/config/ocp90.repo
+            cat src/config/tmp.repo
+            awk '/rhel-9.2-server-ose-4.13/,/^$/' "src/config/tmp.repo" > "src/config/ocp.repo"
+            cat src/config/ocp.repo
             rm "src/config/tmp.repo"
             ;;
     esac
@@ -243,15 +242,27 @@ main () {
             prepare_repos
             ;;
         "build" | "init-and-build-default")  # TODO: change prow job to use init-and-build-default
-            cosa_init "rhel-coreos-9"
+            cosa_init "rhel-coreos-8"
             cosa_build
             ;;
         "rhcos-cosa-prow-pr-ci")
             setup_user
-            cosa_init "rhel-coreos-9"
+            cosa_init "rhel-coreos-8"
+            cosa_build
+            kola_test_qemu
+            ;;
+        "rhcos-86-build-test-qemu")
+            setup_user
+            cosa_init "rhel-coreos-8"
             cosa_build
             kola_test_qemu
             ;;
+        "rhcos-86-build-test-metal")
+            setup_user
+            cosa_init "rhel-coreos-8"
+            cosa_build
+            kola_test_metal
+            ;;
         "rhcos-92-build-test-qemu"|"rhcos-90-build-test-qemu")
             setup_user
             cosa_init "rhel-coreos-9"
@@ -270,16 +281,12 @@ main () {
             cosa_build
             kola_test_qemu
             ;;
-        "scos-9-build-test-metal")
+        "scos-9-build-test-metal" )
             setup_user
             cosa_init "scos"
             cosa_build
             kola_test_metal
             ;;
-        "rhcos-86-build-test-qemu"|"rhcos-86-build-test-metal")
-            # Disabled tests
-            exit 0
-            ;;
         *)
             # This case ensures that we exhaustively list the tests that should
             # pass for a PR. To add a new test in openshift/os:
diff --git a/docs/faq.md b/docs/faq.md
index 2aa848dc..d5ea0380 100644
--- a/docs/faq.md
+++ b/docs/faq.md
@@ -89,15 +89,6 @@ $ rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift-
 
 This is particularly relevant because it's common for OCP/RHCOS to not publish new "bootimages" or disk images unless needed.
 
-### Outside of release image pull specs
-
-At the current time, these floating tags are available:
-
- - quay.io/openshift-release-dev/ocp-v4.0-art-dev:4.13-9.2
- - quay.io/openshift-release-dev/ocp-v4.0-art-dev:4.12
-
-This may change in the future.
-
 ## Q: How do I see which RHEL and RHCOS version is in a release?
 
 Like above, but add `oc image info`:
diff --git a/fedora-coreos-config b/fedora-coreos-config
index e0b38afe..f00040e1 160000
--- a/fedora-coreos-config
+++ b/fedora-coreos-config
@@ -1 +1 @@
-Subproject commit e0b38afe041f77c9ebc4f7d586b00987e8d280f2
+Subproject commit f00040e1616ef244dfe622cad50b876d8087039e
diff --git a/kola-denylist.yaml b/kola-denylist.yaml
index a7f3535c..e6296849 100644
--- a/kola-denylist.yaml
+++ b/kola-denylist.yaml
@@ -3,6 +3,14 @@
 # see: https://github.com/coreos/coreos-assembler/pull/866.
 - pattern: skip-console-warnings
   tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2164765
+- pattern: coreos.ignition.journald-log
+  tracker: https://github.com/coreos/coreos-assembler/issues/1173
+- pattern: ext.config.shared.ignition.stable-boot
+  tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2075085
+  osversion:
+   - rhel-8.6
+  arches:
+  - s390x
 - pattern: ext.config.shared.kdump.crash
   tracker: https://github.com/coreos/coreos-assembler/issues/2725
   arches:
@@ -23,6 +31,12 @@
   tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2080063
   arches:
     - s390x
+- pattern: luks.*
+  tracker: https://github.com/openshift/os/issues/1149
+  arches:
+   - ppc64le
+   - aarch64
+   - s390x
 
 # We're using some COPR stuff intentionally
 - pattern: ext.config.shared.content-origins
@@ -32,8 +46,17 @@
 - pattern: ext.config.version.rhel-matches-rhcos-build
   tracker: ''
 
+# Temporary to unblock COSA CI
+- pattern: ext.config.shared.clhm.network-device-info
+  tracker: https://github.com/openshift/os/issues/1041
+  osversion:
+   - rhel-8.6
+
 - pattern: ext.config.rpm-ostree.replace-rt-kernel
   tracker: https://github.com/openshift/os/issues/1099
 
 - pattern: rhcos.network.*
   tracker: https://github.com/coreos/coreos-assembler/issues/3376
+
+- pattern: ext.config.shared.ignition.resource.remote
+  tracker: https://github.com/openshift/os/issues/1190
diff --git a/manifest-c9s.yaml b/manifest-c9s.yaml
index 5a096ebe..9ec89967 100644
--- a/manifest-c9s.yaml
+++ b/manifest-c9s.yaml
@@ -26,14 +26,14 @@ repos:
   - okd-copr
   - podman-next-copr
   # Include RHCOS 9 repo for oc, hyperkube and conmon-rs
-  - rhel-9.2-server-ose-4.14
+  - rhel-9.2-server-ose-4.13
 
 # We include hours/minutes to avoid version number reuse
-automatic-version-prefix: "414.9.<date:%Y%m%d%H%M>"
+automatic-version-prefix: "413.9.<date:%Y%m%d%H%M>"
 # This ensures we're semver-compatible which OpenShift wants
 automatic-version-suffix: "-"
 # Keep this is sync with the version in postprocess
-mutate-os-release: "4.14"
+mutate-os-release: "4.13"
 
 postprocess:
   - |
@@ -42,7 +42,7 @@ postprocess:
 
      # Tweak /usr/lib/os-release
      grep -v "OSTREE_VERSION" /etc/os-release > /usr/lib/os-release.stream
-     OCP_RELEASE="4.14"
+     OCP_RELEASE="4.13"
      (
      . /etc/os-release
      cat > /usr/lib/os-release <<EOF
diff --git a/manifest-rhel-9.2.yaml b/manifest-rhel-9.2.yaml
index 612e26f1..babaaa56 100644
--- a/manifest-rhel-9.2.yaml
+++ b/manifest-rhel-9.2.yaml
@@ -20,15 +20,14 @@ repos:
   - rhel-9.2-baseos
   - rhel-9.2-appstream
   - rhel-9.2-fast-datapath
-  - rhel-9.2-server-ose-4.13  # FIXME a few things are built only in 4.13 right now, like podman
-  - rhel-9.2-server-ose-4.14
+  - rhel-9.2-server-ose-4.13
 
 # We include hours/minutes to avoid version number reuse
-automatic-version-prefix: "414.92.<date:%Y%m%d%H%M>"
+automatic-version-prefix: "413.92.<date:%Y%m%d%H%M>"
 # This ensures we're semver-compatible which OpenShift wants
 automatic-version-suffix: "-"
 # Keep this is sync with the version in postprocess
-mutate-os-release: "4.14"
+mutate-os-release: "4.13"
 
 postprocess:
   - |
@@ -37,7 +36,7 @@ postprocess:
 
      # Tweak /usr/lib/os-release
      grep -v "OSTREE_VERSION" /etc/os-release > /usr/lib/os-release.rhel
-     OCP_RELEASE="4.14"
+     OCP_RELEASE="4.13"
      (
      . /etc/os-release
      cat > /usr/lib/os-release <<EOF
@@ -121,7 +120,7 @@ repo-packages:
     packages:
       # We want the one shipping in RHEL, not the equivalently versioned one in RHAOS
       - nss-altfiles
-  - repo: rhel-9.2-server-ose-4.14
+  - repo: rhel-9.2-server-ose-4.13
     packages:
       - conmon-rs
       - cri-o
```

Which generally looks sane to me.

**Review by ravanelli — APPROVED** [review]
/lgtm

**Comment by cgwalters** [comment]
Ah, now looks like we're hitting tide ratelimiting.

**Review by dustymabe — COMMENTED** [review]
Everything in here is cherry-picks ✔️ except for the last commit:

```
c9s: Use 9.2 OCP

```

Would be nice to have more context in that commit message. Otherwise LGTM. 

/lgtm

**Comment by cgwalters** [comment]
Thanks for double checking!  Agree on the last commit, I basically ran out of steam in understanding the repo setups here (particularly `prow-entrypoint.sh` and its interactions with the mirrors in release controller etc.)

**Pull request merged**
