### PR TITLE
Add pivot in rdgo

### PR DESCRIPTION
**Pull request by ashcrow**
Signed-off-by: Steve Milner <smilner@redhat.com>

### CODE REVIEW

**Comment by ashcrow** [comment]
This should be merged AFTER the command is added to RHCOS. Working on that now.

**Comment by ashcrow** [comment]
Error is expected. ``pivot`` is not currently built as it's part of this PR.

**Comment by cgwalters** [comment]
That said...we may have to either neuter the Prow job temporarily, or do this in two commits/PRs.  Seems like the latter shouldn't be too hard right?

**Comment by ashcrow** [comment]
@cgwalters this PR now simply adds pivot to rdgo. https://github.com/openshift/os/pull/103 adds doc update and inclusion into the compose.

**Pull request merged**
