### PR TITLE
NO-JIRA: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Aashish Radhakrishnan (1):
      denylist: add snooze for multipath.partition

Dusty Mabe (3):
      tests: add/use common definition for container repo/tag to use
      tests: switch quadlet test to use :latest fedora tag
      tests: only test gdb extension on stable/testing{,-devel}

Jonathan Lebon (2):
      image-base.yaml: compress applehv with gzip, hyperv with zip
      tests: fix boot.bootupd-validate on rhel-9.6

jbtrystram (1):
      overlay/dracut prefix dracut config files with number
```

### CODE REVIEW

**Review by ravanelli — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
Fails on
```
systemctl status kola-runext.service:
× kola-runext.service
     Loaded: loaded (/etc/systemd/system/kola-runext.service; static)
     Active: failed (Result: exit-code) since Thu 2024-11-07 01:39:49 UTC; 536ms ago
   Duration: 1.746s
    Process: 2080 ExecStart=/usr/local/bin/kola-runext-bootupd-validate (code=exited, status=1/FAILURE)
   Main PID: 2080 (code=exited, status=1/FAILURE)
        CPU: 82ms

Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + overwrite=
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + overwrite_file
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + case "$(arch)" in
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2082]: ++ arch
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2083]: ++ realpath /dev/disk/by-partlabel/EFI-SYSTEM
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + local esp_dev=/dev/vda2
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + '[' '!' -b /dev/vda2 ']'
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + mount -v /dev/vda2 /boot/efi
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2084]: mount: /dev/vda2 mounted on /boot/efi.
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2085]: ++ find /boot/efi -name shim.efi
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + local shim_file=/boot/efi/EFI/redhat/shim.efi
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + '[' -z /boot/efi/EFI/redhat/shim.efi ']'
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + echo test
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + umount -v /dev/vda2
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2086]: umount: /boot/efi (/dev/vda2) unmounted
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + overwrite=1
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + '[' -n 1 ']'
Nov 07 01:39:47 qemu0 kola-runext-bootupd-validate[2080]: + bootupctl validate
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2087]: Skipped: BIOS
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2087]: Changed: redhat/shim.efi
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2087]: error: Caught validation errors
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + adopt_and_update
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + local state_file=/boot/bootupd-state.json
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + '[' -f /boot/bootupd-state.json ']'
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + mount -o remount,rw /boot
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + rm -f /boot/bootupd-state.json
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2095]: + grep 'Adopted and updated.*'
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2094]: + bootupctl adopt-and-update
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2095]: Adopted and updated: EFI: grub2-efi-x64-1:2.06-82.el9_4.x86_64,shim-x64-15.8-4.el9_3.x86_64
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + '[' '!' -f /boot/bootupd-state.json ']'
Nov 07 01:39:48 qemu0 kola-runext-bootupd-validate[2080]: + mount -o remount,ro /boot
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2080]: + validate
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2080]: + local 'msg_efi=Validated: EFI'
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2080]: + local 'msg_bios=Skipped: BIOS'
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2080]: + case "$(arch)" in
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2106]: ++ arch
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2108]: + grep 'Skipped: BIOS'
Nov 07 01:39:49 qemu0 kola-runext-bootupd-validate[2107]: + bootupctl validate
Nov 07 01:39:49 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 01:39:49 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
--- [31mFAIL[0m: ext.config.shared.boot.bootupd-validate (53.81s)
        cluster.go:151: Error: Unit kola-runext.service exited with code 1
        cluster.go:151: 2024-11-07T01:39:49Z cli: Unit kola-runext.service exited with code 1
        harness.go:1265: kolet failed: : kolet run-test-unit failed: Process exited with status 1
```

**Comment by travier** [comment]
https://github.com/coreos/fedora-coreos-config/pull/3181#issuecomment-2462333867

**Comment by travier** [comment]
Looks like RHCOS builds are failing on this right now:

```
Executing `postprocess` inline script '8'
+ /usr/bin/bootupctl backend generate-update-metadata
Generated update layout for BIOS: grub2-tools-1:2.06-86.el9_4.1.x86_64
rpm: no arguments given for query
error: generating metadata failed: Failed to invoke rpm -qf
error: Installing packages: bwrap(/usr/bin/rpmostree-postprocess-inline-8): Child process killed by signal 1
failed to execute cmd-build: exit status 1
```

**Comment by jlebon** [comment]
Yeah, I'll add patches to this PR to adapt it for tier-x.

**Comment by jlebon** [comment]
Pushed an update, but actually though as per https://github.com/coreos/fedora-coreos-config/pull/3177#issuecomment-2477478585, I think we need to wait until branching to land this. Is there anything we actually need in 4.18 from this PR?

Hmm OK, "07fix-selinux-labels: fix service ordering" would be good at least to squash the associated systemd warning. So basically:
- add `rhcos-4.18` branch to f-c-c, set at the current commit that the `master` branch here is sitting on
- backport https://github.com/coreos/fedora-coreos-config/pull/3239 to `rhcos-4.18`

**Comment by jlebon** [comment]
Moved this to https://github.com/openshift/os/pull/1658 and added a commit there.

**Comment by jlebon** [comment]
/lgtm

This should fix rhel-9.6 at least.

**Pull request merged**
