### PR TITLE
NO-JIRA: [release-4.15] NO-JIRA: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Jonathan Lebon (1):
      tests/var-mount/scsi-id: simplify bootloader entry finding
```

### CODE REVIEW

**Review by yasminvalim — APPROVED** [review]
LGTM ✅

**Comment by jlebon** [comment]
Added another cherry-pick needed for fixing test failures.

/lgtm

**Review by c4rt0 — APPROVED** [review]
/lgtm

**Review by dustymabe — APPROVED** [review]
/lgtm

**Comment by joepvd** [comment]
/retitle NO-JIRA: [release-4.15] NO-JIRA: Bump fedora-coreos-config

**Pull request merged**
