### PR TITLE
[release-4.13] OCPBUGS-11657: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by ravanelli**
Dusty Mabe (1):
      coreos-teardown-initramfs: teardown after NM has exited

Renata Ravanelli (3):
      overlay.d: create new 30gcp-udev-rules overlay
      overlay.d: Add/Update udev rules for GCP
      Add 30gcp-udev-rules overlay to the manifest

### CODE REVIEW

**Comment by ravanelli** [comment]
/hold 
It is still missing the manifest update

**Comment by dustymabe** [comment]
Are secureboot tests known to be failing? Last two runs show:

```
 Running test: iso-as-disk.uefi-secure
FAIL: iso-as-disk.uefi-secure (10m0s)
    timed out after 10m0s
Running test: iso-as-disk.4k.uefi
PASS: iso-as-disk.4k.uefi (42.912s)
Running test: iso-install.bios
PASS: iso-install.bios (4m30.114s)
Running test: iso-live-login.bios
PASS: iso-live-login.bios (1m5.104s)
Running test: iso-live-login.uefi
PASS: iso-live-login.uefi (55.286s)
Running test: iso-live-login.uefi-secure
FAIL: iso-live-login.uefi-secure (10m0.003s)
    timed out after 10m0s 
```


and:


```
 === RUN   basic
--- FAIL: basic (601.54s)
        harness.go:103: TIMEOUT[10m0s]: SSH unsuccessful within allotted timeframe for 55a62969-9ecf-46b1-b090-ddabd38a2043.
FAIL, output in /logs/artifacts/kola
Error: harness: test suite failed
2023-04-11T16:24:51Z cli: harness: test suite failed
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-kola", line 75, in <module>
    subprocess.check_call(subargs)
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['kola', '-p', 'qemu-unpriv', '--output-dir', '/logs/artifacts/kola', 'run', '--qemu-firmware=uefi-secure', 'basic', '--qemu-memory', '1536']' returned non-zero exit status 1.
error: failed to execute cmd-kola: exit status 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-04-11T16:24:51Z"}
```

**Comment by jlebon** [comment]
Hmm, I think we need to backport https://github.com/openshift/os/pull/1238 to release-4.13?
Probably easier to inline it into this PR.

**Comment by dustymabe** [comment]
> Hmm, I think we need to backport #1238 to release-4.13? Probably easier to inline it into this PR.

Yep. Will do.

**Pull request merged**
