### PR TITLE
tests/kola: use root reprovisioning tests from FCOS

### PR DESCRIPTION
**Pull request by jlebon**
These all work on RHCOS right now.

It overlaps with the `luks/tpm` test, so drop that. Rename the
`luks/ignition` test to `luks-var` to be clearer.

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/coreos-assembler/pull/2072

**Comment by jlebon** [comment]
Prompted by https://github.com/coreos/fedora-coreos-config/pull/878 where we're modifying the LUKS external test.

**Comment by cgwalters** [comment]
Hmm I think there may be some delay in propagating the new Prow config.  Will retry in a bit.

**Comment by cgwalters** [comment]
```
--- PASS: ext.config.root-reprovision.luks (213.63s)
--- PASS: ext.config.root-reprovision.raid1 (174.13s)
```

:tada: 
/lgtm

**Pull request merged**
