### PR TITLE
s390x: Cleanup after fedora-coreos-config bump

### PR DESCRIPTION
**Pull request by jschintag**
Cleaning up after https://github.com/openshift/os/pull/877 landed

### CODE REVIEW

**Comment by jschintag** [comment]
I feel like i shouldn't need to disable that test when it is already disabled for fcos, but i did indeed need to.

**Comment by jschintag** [comment]
Let's check if that is a fluke

/test rhcos-86-build-test-metal

**Review by gursewak1997 — APPROVED** [review]
lgtm

**Comment by travier** [comment]
/hold
It's failing repeatably. Might be an hidden bug here.

**Comment by jschintag** [comment]
Yes, it seems it is failing to start multipath.
```
[  140.961000] systemd[1]: Timed out waiting for device dev-disk-by\x2dlabel-dm\x2dmpath\x2dboot.device.
[  141.052758] systemd[1]: Dependency failed for CoreOS Wait For Multipathed Boot.
[  141.121322] systemd[1]: Dependency failed for Initrd Default Target.
[  141.184977] systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.
         Starting Ensure filesystem labeled `boot` is unique...
[  141.270508] systemd[1]: initrd.target: Triggering OnFailure= dependencies.
[  141.338715] systemd[1]: coreos-multipath-wait.target: Job coreos-multipath-wait.target/start failed with result 'dependency'.
[  141.584674] systemd[1]: dev-disk-by\x2dlabel-dm\x2dmpath\x2dboot.device: Job dev-disk-by\x2dlabel-dm\
x2dmpath\x2dboot.device/start failed with result 'timeout'.
```
[iso-install.zip](https://github.com/openshift/os/files/9046324/iso-install.zip)

**Comment by jschintag** [comment]
I have created https://github.com/openshift/os/pull/878 for now to unblock 4.12.

**Comment by jschintag** [comment]
I rebased for now and added the revert of https://github.com/openshift/os/pull/878 to the bump commit.

**Comment by miabbott** [comment]
@nikita-dubrovskii perhaps the error in the comment above is related to this change `s390x: coreos-gpt-setup: add suport for LUKS encrypted 'boot' partition`

https://github.com/coreos/fedora-coreos-config/commit/e3309ad07ca959d7acda2f2c95f08ac0b4673018

**Comment by miabbott** [comment]
I think it is just a mis-spelling in the dracut module - https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-gpt-setup.sh#L11

`s/DM_MAPTH/DM_MPATH/`

https://github.com/coreos/fedora-coreos-config/pull/1827

**Comment by travier** [comment]
We can rebase this one on top of https://github.com/openshift/os/pull/877

**Comment by jschintag** [comment]
@travier I have rebased it.

**Pull request merged**
