### PR TITLE
[4.10] ci: Work around git checkout security check

### PR DESCRIPTION
**Pull request by travier**
Manual backport of https://github.com/openshift/os/pull/814

### CODE REVIEW

**Comment by miabbott** [comment]
/lgtm

The `validate` job appears to be using the CI job config for `master`, not `release-4.10

/retest

**Comment by miabbott** [comment]
> /lgtm
> 
> The `validate` job appears to be using the CI job config for `master`, not `release-4.10
> 
> /retest

/lgtm cancel

Ugh, too early in the morning to do this....

The commit is using `cosa init --transient` which isn't on the `rhcos-4.10` branch of `cosa`

**Comment by miabbott** [comment]
@travier we'll need a different workaround for the unsafe `git` checkout problem

**Comment by miabbott** [comment]
```
+ git clone /src
fatal: repository '/src' does not exist
```

Looks like the correct path would be `/go/src/github/openshift/os` based on https://github.com/openshift/os/blob/21ea2730e63af11e963fa77985f4110a58fc91f4/ci/Dockerfile#L14

**Comment by travier** [comment]
OK, looks like this workaround works

**Pull request merged**
