### PR TITLE
overlay: Add 45-rhcos-extensions.preset

### PR DESCRIPTION
**Pull request by cgwalters**
This is part of https://github.com/openshift/enhancements/pull/677

https://bugzilla.redhat.com/show_bug.cgi?id=1941342

### CODE REVIEW

**Comment by LorbusChris** [comment]
(Note to myself: Find out what the Kata containers story is on FCOS/OKD)

**Comment by fidencio** [comment]
@cgwalters, thanks for opening the PR!

**Comment by fidencio** [comment]
LGTM, thanks!

**Pull request merged**
