### PR TITLE
Drop docker from compose

### PR DESCRIPTION
**Pull request by ashcrow**
Requires:
- [x] https://github.com/openshift/installer/pull/221 
- [x] https://github.com/openshift/installer/pull/207

### CODE REVIEW

**Comment by ashcrow** [comment]
Required PRs have been merged. PTAL.

**Comment by jlebon** [comment]
That's awesome!
To confirm, this will break `oc cluster up` for now, right?

**Comment by ashcrow** [comment]
@jlebon from my understanding, yes. It also will break other systems which previously hard assumed `docker` was the only container runtime available.

**Pull request merged**
