### PR TITLE
NO-JIRA: faq: add details about RAID installations

### PR DESCRIPTION
**Pull request by jlebon**
We have OpenShift docs for some of this, but it's nice to have it summarized succinctly in this format.

Notably new is the Hybrid RAID path, which still needs to be documented in the OCP docs.

### CODE REVIEW

**Comment by jlebon** [comment]
The Hybrid RAID instructions there still need to be validated.

**Review by jbtrystram — COMMENTED** [review]
Looks sane to me, however i am not able to reproduce and verify.
Quick question: in the mdadm raid option, you still need to have a non-raid EFI partition right?  how would you boot otherwise?

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Feels a bit like magic to me :)

**Comment by jlebon** [comment]
> Quick question: in the mdadm raid option, you still need to have a non-raid EFI partition right? how would you boot otherwise?

No, it's on top of the RAID. The RAID setup is understood by the firmware.

**Review by mtkaczyk — COMMENTED** [review]
I didn't mention is earlier because there was no time and need too but..

In normal environment we should refer to the MD devices via named links, which are resist in "/dev/md/" directory.

Assumptions that:
 /dev/md127 - container
/dev/md126 - vol0
/dev/md125 - vol1
should work in 99% cases but if there is other MD raid array (/dev/md127 is occupied) then md device number could be different than we hardcoded here.

Should we care? I  Maybe we should warn here? For reference see:
https://www.intel.com/content/dam/support/us/en/documents/memory-and-storage/linux-intel-vroc-userguide-333915.pdf

chapter `4.3.1 Block Device of Intel® VROC RAID Volume`

I don't like how it is implemented in mdadm but any changes in this area are harmful for users.. They sticked to it.

**Comment by travier** [comment]
/title NO-JIRA: faq: add details about RAID installations

**Comment by travier** [comment]
/retitle NO-JIRA: faq: add details about RAID installations

**Comment by travier** [comment]
I'll let Jonathan see if something is needed for https://github.com/openshift/os/pull/1471#pullrequestreview-1978879863 and remove the hold

**Comment by mtkaczyk** [comment]
> One thing is I think now when we re-assemble after deleting the dummy, we can't just use `mdadm -As`, right? We need to do it more directly so that we can specify the md name IIUC. I went with `mdadm -A /dev/md/coreos /dev/md/imsm0`. Let me know if that doesn't look correct.

Personally, I don't like `assemble (-A)` because it is really complicated and it is almost impossible to not have regressions there but in general it should work. I tested the command on my platform and it appears to work.

If you will use `mdadm -As` or `mdadm -I /dev/md/imsm0`, raid device md link will get `_0` suffix, this is something not wanted here (confusing for users).

```
lrwxrwxrwx  1 root root    8 Apr  8 10:26 imsm0 -> ../md127
lrwxrwxrwx  1 root root    8 Apr  8 10:26 vol_0 -> ../md125
lrwxrwxrwx  1 root root    8 Apr  8 10:26 vol1_0 -> ../md126
```

The standard flow, used in system and installers (more reliable, deeply tested) is:
```
mdadm -Eb /dev/md/imsm0 > mdadm_tmp.conf
mdadm -I /dev/md/imsm -c tmp_mdadm.conf
```
We are creating temporary config file, and then passing it to `Incremental` command. With that, mdadm knows that metadata can be considered as trusted and we should not append suffix.

Both ways are correct, second is less risky as it is commonly used. There are no issues in you command.

Btw. if we can inject this conf file to `/etc/mdadm.conf` for both initramfs and regular system, then they will be named same after booting to system. I think that currently they will receive `_0` suffix. This is not an issue unless customers are complying, just FYI :)

**Comment by jlebon** [comment]
Ack, thanks for the confirmation. :)

The temporary config file approach seems interesting. Though since we're modifying the container while it's offline, will `mdadm -I ... -c tmp_mdadm.conf` still work even though the config file will mention the old dummy RAID0 that was deleted?

Yeah, re. the installed system, I don't think customers or the system need to care in practice of the naming used in the actual booted system. But it's good to be aware of the config-related commands.

Anyway, if the docs as written look good to you (and especially if you've tested it), then I'd say let's go with that. Unfortunately, I'm not in a position to retest changes to the procedure very easily so I'm hesitant to tweak it further.

/hold cancel

**Comment by mtkaczyk** [comment]
> The temporary config file approach seems interesting. Though since we're modifying the container while it's offline, will `mdadm -I ... -c tmp_mdadm.conf` still work even though the config file will mention the old dummy RAID0 that was deleted?

Config is just a hint, which says "hey, this array can be deeply trusted because it is described in config".
In config each IMSM array is defined as separated entity, so simply if there is no array metadata on drives (array is deleted) mdadm will not try to assemble this raid volume and config entry will be ignored.

If UUID is still same after deleting one volume then old config will work, if UUID changed you can regenerate it.

**Pull request merged**
