### PR TITLE
OWNERS: Add Adam Piasecki (c4rt0)

### PR DESCRIPTION
**Pull request by c4rt0**
Modified content as instructed by provided documentation.

### CODE REVIEW

**Comment by travier** [comment]
Can you make the commit title a little bit more descriptive? Something like:
```
OWNERS: Add myself (XYZ)
```

Thanks!

**Comment by c4rt0** [comment]
> Can you make the commit title a little bit more descriptive? Something like:
> 
> ```
> OWNERS: Add Adam Piasecki (c4rt0)
> ```
> 
> Thanks!

Thanks @travier - correction implemented, suggestion recorded.

**Comment by travier** [comment]
Hum, you've modified the title of this PR but not the commit title :)

**Pull request merged**
