### PR TITLE
tests: Add `skip-console-warnings` to global kola config

### PR DESCRIPTION
**Pull request by cgwalters**
Until https://bugzilla.redhat.com/show_bug.cgi?id=2164765 is fixed.

### CODE REVIEW

**Comment by jlebon** [comment]
/lgtm cancel

Wait, shouldn't this have something like:

```yaml
  osversion:
    - c9s
    - rhel-9.0
```

**Comment by cgwalters** [comment]
> Wait, shouldn't this have something like:

Yes...but we're not going to care about rhel8 *very* quickly on this branch so...does it matter?

**Comment by dustymabe** [comment]
Note that with this change we're now ignoring other failures:

```
[2023-02-07T22:03:13.487Z] === RUN   basic
[2023-02-07T22:03:39.977Z] === RUN   basic/MachineID
[2023-02-07T22:03:39.977Z] === RUN   basic/RHCOSGrowpart
[2023-02-07T22:03:39.977Z] === RUN   basic/PortSSH
[2023-02-07T22:03:39.977Z] === RUN   basic/DbusPerms
[2023-02-07T22:03:39.977Z] === RUN   basic/ServicesActive
[2023-02-07T22:03:39.977Z] === RUN   basic/ReadOnly
[2023-02-07T22:03:39.977Z] === RUN   basic/Useradd
[2023-02-07T22:03:40.897Z] 2023-02-07T22:03:40Z kola: Found systemd generator failure (/usr/lib/systemd/system-generators/podman-system-generator) on machine 1c7134f1-2fdd-4c7f-a3ad-3523d6bd364a console
[2023-02-07T22:03:40.897Z] --- PASS: basic (27.44s)
```

**Pull request merged**
