### PR TITLE
ci: Remove version selection script

### PR DESCRIPTION
**Pull request by travier**
Remove the current multi-version setup that was merged in https://github.com/openshift/os/pull/852 as we are moving to a COSA based setup.

### CODE REVIEW

**Comment by travier** [comment]
I'm removing that now before the alternative is ready to avoid creating dependencies on it.

**Comment by travier** [comment]
CC @jlebon

**Comment by miabbott** [comment]
> Remove the current multi-version setup that was merged in #852 as we are moving to a COSA based setup.

This looks fine, but is there context/breadcrumbs on how we are going to select the version via `coreos-assembler`?

**Comment by travier** [comment]
Yes, the plan for COSA is in https://github.com/coreos/coreos-assembler/pull/2934

**Pull request merged**
