### PR TITLE
Bug 1987276: [release-4.7] Move 4.7 to RHEL 8.4

### PR DESCRIPTION
**Pull request by travier**
This includes some smaller cherry-picked fixes from 4.8.

### CODE REVIEW

**Comment by travier** [comment]
This needs the corresponding `redhat-coreos-release` package to exist to successfully build.

**Comment by miabbott** [comment]
I don't see the point in creating a BZ for the use of RHEL 8.4 in 4.8 just to satisfy the BZ bot, so let's just waive the invalid flag.

**Comment by miabbott** [comment]
> I don't see the point in creating a BZ for the use of RHEL 8.4 in 4.8 just to satisfy the BZ bot, so let's just waive the invalid flag.

Silly me thinking I was better than a bot...

The *other* bot managing Bugzilla bugs keeps resetting the Target Release on the 4.7.z BZ, so I am going to do the needful and create the necessary BZs to appease that bot.

**Comment by miabbott** [comment]
/bugzilla refresh

_/me gets more coffee_

**Comment by miabbott** [comment]
Still waiting for the latest `redhat-release-coreos` RPM to show up on the sync'ed repo

```
bash-4.4$ curl -Ls http://base-4-7-rhel8.ocp.svc.cluster.local/rhel-8-server-ose/Packages/ | grep redhat-release-coreos
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="redhat-release-coreos-47.82-1.el8__x86_64/">redhat-release-coreos-47.82-1.el8__x86_64/</a></td><td align="right">19-Nov-2020 19:55  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="redhat-release-coreos-47.83-1.el8__x86_64/">redhat-release-coreos-47.83-1.el8__x86_64/</a></td><td align="right">20-May-2021 02:26  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="redhat-release-coreos-47.83-1.el8__x86_64__fd431d51/">redhat-release-coreos-47.83-1.el8__x86_64__fd431d51/</a></td><td align="right">19-May-2021 20:26  </td><td align="right">  - </td><td>&nbsp;</td></tr>
<tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="redhat-release-coreos-47.83-2.el8__x86_64__fd431d51/">redhat-release-coreos-47.83-2.el8__x86_64__fd431d51/</a></td><td align="right">19-May-2021 20:27  </td><td align="right">  - </td><td>&nbsp;</td></tr>
```

**Pull request merged**
