### PR TITLE
common.yaml: stop using `initramfs-args` in favour of `dracut.conf.d` dropins

### PR DESCRIPTION
**Pull request by jlebon**
The field is deprecated:
https://github.com/coreos/rpm-ostree/pull/3834

See individual commit messages for details.
Closes: #1377

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Awesome series.  I assume so but worth verifying: Did you compare the before/after of the `lsinitrd`?

Also tangentially related to:

> It just stops uselessly generating ifcfg files in the initrd.

Could this be related to https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/NetworkManager-clean-initrd-state.yaml which I started to look at and then recoiled in horror and closed the tab...

**Comment by jlebon** [comment]
I hadn't checked closely the diff, but I did now and one thing that jumps out is that `ifcfg` was still getting pulled in. I opened https://github.com/coreos/fedora-coreos-config/pull/2642 and https://github.com/dracutdevs/dracut/pull/2529 for that.

**Comment by jlebon** [comment]
To be clear, this needs to wait until https://github.com/coreos/fedora-coreos-config/pull/2640 lands in RHCOS.

/hold

**Comment by jlebon** [comment]
> Could this be related to [openshift/machine-config-operator@`master`/templates/common/_base/files/NetworkManager-clean-initrd-state.yaml](https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/NetworkManager-clean-initrd-state.yaml?rgh-link-date=2023-09-28T21%3A23%3A53Z) which I started to look at and then recoiled in horror and closed the tab...

I'm not sure what that script is doing. It seems to be doing something that shouldn't normally be necessary and doesn't talk about how it intersects with the teardown scripts we have and the existing behaviour of not stomping on user configs. Probably deserves a chat with the team that introduced it.

**Comment by jlebon** [comment]
> To be clear, this needs to wait until [coreos/fedora-coreos-config#2640](https://github.com/coreos/fedora-coreos-config/pull/2640) lands in RHCOS.
> 
> /hold

This landed as part of https://github.com/openshift/os/pull/1371.

/hold cancel

**Pull request merged**
