### PR TITLE
Makefile more

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by peterbaouoft** [comment]
/me is testing the content out :). Also, seems like rebase is needed after #17 has been merged?

**Comment by jlebon** [comment]
LGTM too, though we should be working towards embedding an existing commit into the container, right?

**Comment by jlebon** [comment]
I guess we want both: new tree in a container for testing out stuff, but slurping up an existing tree for actual pipeline integration.

**Comment by ashcrow** [comment]
> I guess we want both: new tree in a container for testing out stuff, but slurping up an existing tree for actual pipeline integration.

I'd like the same content used in both eventually, but this works for the moment.

**Comment by peterbaouoft** [comment]
Ah, nvm, the same commit was included from #17, and looks like robot can recognize & ignore the same commit. Interesting and good to know =).

**Pull request merged**
