### PR TITLE
Makefile: Use download.fp.org for mirrors

### PR DESCRIPTION
**Pull request by jlebon**
This will automatically redirect to a close mirror.

### CODE REVIEW

**Comment by jlebon** [comment]
/hold
I'm just gonna tweak the docs as well in this one.

**Comment by cgwalters** [comment]
The downside is going back to mirror roulette :game_die: though.  But it's fine by me.

**Comment by jlebon** [comment]
OK, dumped some more info in here!
/hold cancel

**Comment by cgwalters** [comment]
Merging until we're out of low tide, so to speak.

**Pull request merged**
