### PR TITLE
DO NOT MERGE: rdgo: Add dracut-bootengine

### PR DESCRIPTION
**Pull request by ashcrow**
Wait for work in https://github.com/dustymabe/bootengine to stabilize before merge.

### CODE REVIEW

**Comment by ashcrow** [comment]
Failure is expected for now.

**Comment by dustymabe** [comment]
I'm working on added the dracut modules directly into the ignition package (as a subpackage). I don't think this will be needed.

**Comment by ashcrow** [comment]
Being a subpackage we can drop the build portion as  noted. We'll still need to bring said subpackage into the compose, correct?

**Comment by dustymabe** [comment]
yep. was going to work on that soon and try to open a PR

**Comment by ashcrow** [comment]
SGTM. Closing this as it will be replaced by @dustymabe's PR.

**Pull request closed without merging**
