### PR TITLE
NO-JIRA: ci/prow-entrypoint: Check for whitespace and missing end of line

### PR DESCRIPTION
**Pull request by travier**
*: Fix whitespace at the end of line & missing empty line at end of file

---

ci/prow-entrypoint: Check for whitespace and missing end of line

See: https://github.com/coreos/fedora-coreos-config/pull/2960

### CODE REVIEW

**Comment by travier** [comment]
Needs: https://github.com/coreos/fedora-coreos-config/pull/2960

**Comment by travier** [comment]
Now waiting for https://github.com/openshift/os/pull/1484

**Review by jbtrystram — APPROVED** [review]
/lgtm

**Comment by jbtrystram** [comment]
/retitle NO-JIRA: ci/prow-entrypoint: Check for whitespace and missing end of line

**Pull request merged**
