### PR TITLE
Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by bgilbert**
```
Benjamin Gilbert (6):
      workflows: limit permissions to reading repo contents
      overlay: use Ignition result.json
      ci: use coreos-ci-lib wrapper for kola testiso
      ci: run kola basic scenarios
      tests/misc-ro: check initrd for non-executable scripts
      05core/coreos-liveiso-success: fix hang with systemd 239

Dusty Mabe (10):
      lockfiles: initial aarch64 lockfile
      denylist: snooze podman.network-single on openstack
      manifests: workaround F37 GPG key issue for rawhide
      kola-denylist: snooze the toolbox test
      tests/misc-ign-ro: wait while kube-watch is activating
      Revert "manifests: workaround F37 GPG key issue for rawhide"
      denylist: fix snooze definition for ext.config.toolbox
      overrides: fast-track podman-3.3.0-1.fc34
      kola-denylist: extend snooze for the toolbox test
      tests/countme: add support for 4/4 successful requests

Jonathan Lebon (5):
      overrides: fast-track coreos-installer-0.10.0-1.fc34
      image-base: drop useless `sysroot-readonly: true`
      ci/remove-graduated-overrides: enable for branched and rawhide
      ci/remove-graduated-overrides: prefix PRs with branch name
      manifests/fedora-coreos-base: stop disabling modular repos

Micah Abbott (1):
      misc-ign-ro: change message from kube-watch to be more unique

Saqib Ali (1):
      tests: Split up some ro tests and mark tests as non-exclusive

Sohan Kunkerkar (2):
      lockfiles: fast-track Ignition v2.12.0
      15fcos: print warning If Ignition is run more than once

Timothée Ravier (5):
      tests/misc-ro: Simplify permission checks for files in /etc
      15fcos: Order coreos-check-ssh-keys before systemd-user-sessions
      overaly/preset: Enable Count Me by default
      tests/rpm-ostree-countme: Remove now uneeded custom Butane config
      tests/countme: Retry five times to avoid flakes

gursewak1997 (2):
      tests/kola/authentication/passwd: Added tests for password authentication
      tests/kola/podman/dns: Added test for DNS in rootless podman network
```

### CODE REVIEW

**Comment by cgwalters** [comment]
@miabbott what's going on with this container-selinux thing?  Should we revert it for now?

**Comment by miabbott** [comment]
> @miabbott what's going on with this container-selinux thing? Should we revert it for now?

I have the request to get it tagged for 4.10 in flight, but you know how that goes.

We should be able to revert the change in #616 to unblock 4.10 builds until the RPM is properly tagged.  (The new version of `container-selinux` fixes RHBZ#1999245 and shouldn't be critical to building 4.10 at this time)

**Comment by miabbott** [comment]
Revert in https://github.com/openshift/os/pull/621

**Review by sohankunkerkar — APPROVED** [review]

**Pull request merged**
