### PR TITLE
s390x: snooze failing tests till 2022-02-28

### PR DESCRIPTION
**Pull request by jschintag**
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

### CODE REVIEW

**Review by bgilbert — APPROVED** [review]
LGTM

**Review by HuijingHei — APPROVED** [review]

**Comment by miabbott** [comment]
The CI job appears to still be pulling the old `fedora-coreos-config` commit (not the one from #714)

```
Submodule 'fedora-coreos-config' (https://github.com/coreos/fedora-coreos-config) registered for path 'fedora-coreos-config'
Cloning into '/tmp/tmp.eVimABOvqH/src/config.writable/fedora-coreos-config'...
Submodule path 'fedora-coreos-config': checked out '82f22f92620b60b009e94872a7b44fade8e782e1'
```

I'm going to see if I can override/skip the test since this PR doesn't affect the tests/build of `x86_64`

/override ci/prow/build-test-qemu 
/skip

**Pull request merged**
