### PR TITLE
compose-post: Remove readahead

### PR DESCRIPTION
**Pull request by cgwalters**
See https://bugzilla.redhat.com/show_bug.cgi?id=1594984

### CODE REVIEW

**Comment by ashcrow** [comment]
Does this fix the upstream bug, or keep RHCOS from inheriting it (or both)?

**Comment by cgwalters** [comment]
> Does this fix the upstream bug, or keep RHCOS from inheriting it (or both)?

Ah...upstream being...RHEL?  RHELAH?  systemd?  I personally have been thinking of RHCOS as upstream of RHELAH, i.e. we do things first here.  As far as systemd it's long since dead there.

**Comment by jlebon** [comment]
Interesting, I hadn't heard of it before. It seems like something more geared towards desktops than servers. Given that it's already nuked upstream, I agree we should just drop it here as well.

/lgtm

**Comment by ashcrow** [comment]
> Ah...upstream being...RHEL? RHELAH? systemd? 

Apologies, I meant does this PR fix the bugzilla bug linked, or is it just a reference to a problem that we are fixing in RHCOS.

**Comment by cgwalters** [comment]
>  I meant does this PR fix the bugzilla bug linked,

Yep!  Next I'll "backport" to RHELAH.

**Pull request merged**
