### PR TITLE
COS-2769: bump version to 4.17

### PR DESCRIPTION
**Pull request by mike-nguyen**
4.16 branched so bump the version in main development to 4.17.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
/hold
until ART plashet gets added to internal repos. Reviews welcomed still.

**Comment by jlebon** [comment]
There are a few more places that need to be updated. Try a `git grep 4\\.16`.

**Comment by mike-nguyen** [comment]
> There are a few more places that need to be updated. Try a `git grep 4\\.16`.

Thanks there was a lot more!  I will update the branching doc with this PR as a reference.

**Comment by mike-nguyen** [comment]
/hold cancel
ART repos are are added and merged.  It looks like we need the art plashet for 4.17 mirrored in CI which is causing the failures.

**Comment by jlebon** [comment]
> rpm-md repo 'rhel-9.4-baseos'; generated: 2024-05-02T07:02:38Z solvables: 0
> rpm-md repo 'rhel-9.4-appstream'; generated: 2024-05-02T07:16:36Z solvables: 0

Huh, the repos are empty. Ahh, I think we need https://github.com/openshift/release/pull/52325 at least.

**Comment by mike-nguyen** [comment]
there are rhaos packages are old in the ART plashet causing kola test failures

Also seeing this in the prow/validate job which I've never seen before. Did something change or is something more strict than before?
```
+ git clone /go/src/github.com/openshift/os os
Cloning into 'os'...
fatal: detected dubious ownership in repository at '/go/src/github.com/openshift/os/.git'
To add an exception for this directory, call:

	git config --global --add safe.directory /go/src/github.com/openshift/os/.git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
{"component":"entrypoint","error":"wrapped process failed: exit status 128","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-05-22T01:06:47Z"} 
[36mINFO[0m[2024-05-22T01:06:49Z] Ran for 2m56s                                
[31mERRO[0m[2024-05-22T01:06:49Z] Some steps failed:                           
[31mERRO[0m[2024-05-22T01:06:49Z] 
  * could not run steps: step validate failed: test "validate" failed: could not watch pod: the pod ci-op-7tttzwgt/validate failed after 52s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 128, reason Error
```

**Comment by jlebon** [comment]
Do you have a ticket already for the rebuilds necessary? We could also temporarily denylist it.

> Also seeing this in the prow/validate job which I've never seen before. Did something change or is something more strict than before?

Added another commit for that one!

**Comment by mike-nguyen** [comment]
> Do you have a ticket already for the rebuilds necessary? We could also temporarily denylist it.
> 
> > Also seeing this in the prow/validate job which I've never seen before. Did something change or is something more strict than before?
> 
> Added another commit for that one!

@haircommander helped us by building conmon and cri-o with the correct brew tags. We are still waiting for conmon-rs which is usually built by @jnovy

**Comment by mike-nguyen** [comment]
The cri-o rebuild is blocked on RHEL-35883. We may need to skip the test for now.

**Review by travier — APPROVED** [review]
/lgtm

**Comment by travier** [comment]
```
Running test: iso-offline-install.bios
FAIL: iso-offline-install.bios (10m0.002s)
    timed out after 10m0s
Running test: iso-offline-install.mpath.bios
FAIL: iso-offline-install.mpath.bios (10m0.004s)
    timed out after 10m0s
Running test: iso-offline-install-fromram.4k.uefi
FAIL: iso-offline-install-fromram.4k.uefi (10m0.001s)
    timed out after 10m0s
Running test: miniso-install.bios
FAIL: miniso-install.bios (10m0.002s)
    timed out after 10m0s
Running test: miniso-install.nm.bios
FAIL: miniso-install.nm.bios (10m0.007s)
    timed out after 10m0s
Running test: miniso-install.4k.uefi
FAIL: miniso-install.4k.uefi (10m0s)
    timed out after 10m0s
Running test: miniso-install.4k.nm.uefi
FAIL: miniso-install.4k.nm.uefi (10m0.001s)
    timed out after 10m0s
Running test: pxe-offline-install.bios
FAIL: pxe-offline-install.bios (10m0s)
    timed out after 10m0s
Running test: pxe-offline-install.4k.uefi
FAIL: pxe-offline-install.4k.uefi (10m0.002s)
    timed out after 10m0s
Running test: pxe-online-install.bios
FAIL: pxe-online-install.bios (10m0.005s)
    timed out after 10m0s
Running test: pxe-online-install.4k.uefi
FAIL: pxe-online-install.4k.uefi (10m0.008s)
    timed out after 10m0s
Error: harness: test suite failed
```

Hum, why is SCOS running the UEFI tests?

**Comment by jlebon** [comment]
Updated this now to pin selinux-policy due to https://github.com/openshift/os/issues/1514.

**Comment by jlebon** [comment]
And Mike's changes
/lgtm

**Pull request merged**
