### PR TITLE
Remove now unneeded sync-sources.sh script

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Review by ashcrow — APPROVED** [review]

**Comment by miabbott** [comment]
`+ fatal 'NetworkManager package changed from rhaos4.7 branch. Needs investigation.' ` looks like RHEL released a new version of `NetworkManager` that we need to get bumped for RHCOS.

Nice to have another CI system while the internal build cluster is on fire.

**Comment by travier** [comment]
We can probably override this one as it is unlikely to need testing :)

**Comment by cgwalters** [comment]
(Agree but it'd still be good to get CI fixed, although we can also just sprint to 8.4)

**Pull request merged**
