### PR TITLE
build-test-qemu: dynamically determine the repo version to use

### PR DESCRIPTION
**Pull request by miabbott**
Determine the repo version to use based on the contents of the manifest.

Also, some ShellCheck fixes

### CODE REVIEW

**Comment by miabbott** [comment]
Open to better solutions :smile:

**Comment by cgwalters** [comment]
I think the slightly cleaner solution would use `rpm-ostree compose tree --print-only src/config/manifest.yaml | jq -r '.["mutate-os-release"]'`:

```
$ walters@toolbox /v/s/w/b/rhcos-master> rpm-ostree compose tree --print-only src/config/manifest.yaml | jq -r '.["mutate-os-release"]'
4.8
$
```

**Comment by cgwalters** [comment]
> Also, some ShellCheck fixes

Almost every time I fight shellcheck I keep thinking "I pinky swear to myself to never write new shell script again", and then I write new shell script again.

**Comment by miabbott** [comment]
My git-fu failed me and I ended up squashing the two commits into one.

**Comment by miabbott** [comment]
Looks like a flake

`error: error creating buildah builder: Error initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-7z424rtf/pipeline@sha256:551299956f10679210b8c179784fca165274435cc2ad6bde58ee23dceb402793: error pinging docker registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp 172.30.228.83:5000: i/o timeout`

Chatter on the internal Slack says that `builld02` is down  :(

**Comment by miabbott** [comment]
`build02` should be healthy again

/retest

**Review by lucab — APPROVED** [review]
/lgtm

**Pull request merged**
