### PR TITLE
OCPBUGS-3455: [release-4.12] gitmodules: use rhcos-4.12 branch for fedora-coreos-config

### PR DESCRIPTION
**Pull request by mike-nguyen**

### CODE REVIEW

**Comment by jlebon** [comment]
CI is failing on the homedir issue. I cherry-picked https://github.com/mike-nguyen/os/commit/41e1506947bf111515ce51d0d1c799c3bf718bdb into this.

/lgtm

**Comment by mike-nguyen** [comment]
Thanks @jlebon!

**Pull request merged**
