### PR TITLE
ci: Enable more tests for RHCOS 9

### PR DESCRIPTION
**Pull request by travier**
Test PR to have CI runs to figure out broken kola tests.

### CODE REVIEW

**Comment by HuijingHei** [comment]
@travier could you help to pick https://github.com/openshift/os/pull/952? Or maybe I can create PR to this branch?

**Comment by travier** [comment]
No need to pick it here as your PR is now good enough as the tests are running there.

**Comment by travier** [comment]
I'll rebase this one once it merges.

**Comment by travier** [comment]
This is failing due to https://github.com/openshift/os/issues/979

**Review by cgwalters — APPROVED** [review]

**Comment by travier** [comment]
SCOS failures are already tracked in issues. RHCOS failures have to be investigated.

**Comment by HuijingHei** [comment]
> SCOS failures are already tracked in issues. RHCOS failures have to be investigated.

I will have a look at RHCOS9 failures tomorrow.

**Comment by cgwalters** [comment]
I think https://github.com/openshift/os/pull/1094 and https://github.com/openshift/os/pull/1094 and https://github.com/coreos/coreos-assembler/pull/3275 should fix all these.

**Comment by travier** [comment]
Thanks Colin!

**Comment by travier** [comment]
```
3755 metadata, 25013 content objects imported; 2.8?GB content written
Wrote commit: 7f8b0400aa2adfcdcf27636030762655baa2acb7e844d3513cbaed3323532d67
[0m[31merror: [0mUpdating '/tmp/cosa/tmp/treecompose.changed': Cannot allocate memory
```

**Comment by travier** [comment]
(mis-clicked) 🤦🏻

**Comment by cgwalters** [comment]
> Dec 13 17:52:27.648241 kola-runext-replace-rt-kernel[1832]: + curl -sSLf --remote-name-all http://mirror.stream.centos.org/9-stream//BaseOS/x86_64/os/Packages/kernel-5.14.0-196.el9.x86_64.rpm http://mirror.stream.centos.org/9-stream//BaseOS/x86_64/os/Packages/kernel-core-5.14.0-196.el9.x86_64.rpm http://mirror.stream.centos.org/9-stream//BaseOS/x86_64/os/Packages/kernel-modules-5.14.0-196.el9.x86_64.rpm http://mirror.stream.centos.org/9-stream//BaseOS/x86_64/os/Packa

OK yep, that already went away :cry: Fixing this to scan for the available kvers etc. is possible, just more work...  or I guess we could archive these fixed kernel versions in a separate place.

**Comment by cgwalters** [comment]
Rebased :surfer:

**Comment by travier** [comment]
> @travier: you cannot LGTM your own PR.

CC @cgwalters :)

**Pull request merged**
