### PR TITLE
denylist: Extend luks to s390x

### PR DESCRIPTION
**Pull request by cgwalters**
We also hit it there.

### CODE REVIEW

**Comment by cgwalters** [comment]
No need to run CI for denylist additions
/override ci/prow/scos-9-build-test-qemu
/override ci/prow/scos-9-build-test-metal
/override ci/prow/rhcos-90-build-test-qemu
/override ci/prow/rhcos-90-build-test-metal
/override ci/prow/rhcos-86-build-test-qemu
/override ci/prow/rhcos-86-build-test-metal

**Comment by cgwalters** [comment]
Arg, had a commit merge to master so prow wants to retest.  Rebased

**Comment by c4rt0** [comment]
I'm just curious, what's `luks` - is it as per google: The Linux Unified Key Setup (LUKS)?

**Comment by cgwalters** [comment]
> I'm just curious, what's luks - is it as per google: The Linux Unified Key Setup (LUKS)?

Yep!  More information in the links from https://github.com/coreos/fedora-coreos-config/pull/2226 as there's some bug (kernel or userspace, we're not sure) that is causing the encryption setup on firstboot to flake and fail.

**Comment by cgwalters** [comment]
Man, so close to just pressing the merge button

**Review by c4rt0 — COMMENTED** [review]
/lgtm

**Pull request merged**
