### PR TITLE
[release-4.15] OCPBUGS-35749: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Jonathan Lebon (1):
      overlays: drop `coreos-multipath-trigger.service`
```

### CODE REVIEW

**Comment by travier** [comment]
/lgtm
It needs some small CI backport

**Comment by jlebon** [comment]
Added a cherry-pick for https://github.com/openshift/os/commit/630d3f3d9c530c238e03c93210598101eafca266.

**Pull request merged**
