### PR TITLE
OCPBUGS-3364: [release-4.10] bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by dustymabe**
```
$ git shortlog --no-merges 8dd05e0..4664a23
Dusty Mabe (1):
      tests/root-reprovision: bump timeout for reprovision tests to 15m

Jonathan Lebon (1):
      tests/kola/root-reprovision: add `reprovision` tag
```

### CODE REVIEW

**Comment by mike-nguyen** [comment]
/retitle OCPBUGS-3364: [release-4.10] bump fedora-coreos-config

**Comment by dustymabe** [comment]
I think I'm just going to override CI here. It's not going to pass because of https://github.com/openshift/os/pull/1058#issuecomment-1307533776

**Comment by mike-nguyen** [comment]
Sounds good to me.

**Pull request merged**
