### PR TITLE
[release-4.10] OCPBUGS-6692: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by c4rt0**
Colin Walters (1):
      [rhcos-4.10] overlay/35-coreos-live: Lazily unmount /proc/cmdline

Dusty Mabe (1):
      .cci.jenkinsfile: disable testing on older RHCOS branch

Micah Abbott (1):
      manifests: move location of nvme-cli for sharing with RHCOS

### CODE REVIEW

**Comment by travier** [comment]
Needs a 4.10 backport of https://github.com/openshift/os/pull/1172

**Comment by c4rt0** [comment]
@travier, can I get the `backport-risk-assessed` label here?

**Comment by travier** [comment]
We don't need the second commit here as that's not the script used for Prow CI.

**Comment by c4rt0** [comment]
> Needs a 4.10 backport of #1172

I think I got confused with this.

**Comment by travier** [comment]
> > Needs a 4.10 backport of #1172
> 
> I think I got confused with this.

Yes, sorry. I did not check properly if the script here needed adjustment before suggestion the backport.

**Pull request merged**
