### PR TITLE
Include pivot

### PR DESCRIPTION
**Pull request by ashcrow**
Requires #98

### CODE REVIEW

**Comment by cgwalters** [comment]
The rdgo build is failing https://continuous-infra-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/rhcos/job/coreos-rhcos-rdgo/1301/artifact/log/failed/pivot/build.log

It looks like pivot assumes it's in a git repo.

**Comment by jlebon** [comment]
A bit late to the party, but why do we need to include this in the host? We just need it to get to the host, right? Or is RHCOS also on double duty as the bootstrap OS for now?

**Comment by ashcrow** [comment]
> Or is RHCOS also on double duty as the bootstrap OS for now?

Right :-). The ``README.md`` already explains how to do it manually. This makes it easier.

**Pull request merged**
