### PR TITLE
dont-merge: marmijo testing Prow jobs timing out

### PR DESCRIPTION
**Pull request by marmijo**
I'm using this test commit and PR to investigate why our Prow jobs are timing out.

### CODE REVIEW

**Comment by mike-nguyen** [comment]
`0/39 nodes are available: 1 node(s) were unschedulable, 14 node(s) had untolerated taint {node-role.kubernetes.io/ci-tests-worker: }, 2 node(s) had untolerated taint {node-role.kubernetes.io/ci-longtests-worker: ci-longtests-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/ci-prowjobs-worker: ci-prowjobs-worker}, 3 node(s) had untolerated taint {node-role.kubernetes.io/infra: }, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 5 Insufficient memory, 6 Insufficient devices.kubevirt.io/kvm, 7 node(s) had untolerated taint {node-role.kubernetes.io/ci-builds-worker: ci-builds-worker}. no new claims to deallocate, preemption: 0/39 nodes are available: 33 Preemption is not helpful for scheduling, 6 No preemption victims found for incoming pod.`  

This is what I grabbed from the events.  Looks like its unable to schedule the pods because some taints on the nodes. There may be none with virt available.  Check with the test platform team.

**Comment by marmijo** [comment]
Closing this because https://github.com/openshift/os/issues/1551 is resolved now

**Pull request closed without merging**
