### PR TITLE
add conmon-rs to RHCOS

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
/retest

(added a build of conmon-rs to OKD COPR)

**Comment by cgwalters** [comment]
/lgtm
but it'd be nice in the future to try adding [a kola test](https://coreos.github.io/coreos-assembler/kola/external-tests/) for this too that configures podman to use it perhaps?

**Comment by cgwalters** [comment]
Flaked on RAID bits, clearly not related
/override ci/prow/scos-9-build-test-qemu

**Comment by haircommander** [comment]
nvm it's there https://github.com/openshift/os/commit/e5d6e2b1311e6d3edacf66556dc09c7c1ae31abf

**Pull request merged**
