### PR TITLE
OCPBUGS-18833: google_nvme_id: sync with latest upstream version

### PR DESCRIPTION
**Pull request by HuijingHei**
Sync with https://github.com/GoogleCloudPlatform/guest-configs/pull/56

Probably fixes: [OCPBUGS-18833](https://issues.redhat.com/browse/OCPBUGS-18833)

### CODE REVIEW

**Comment by HuijingHei** [comment]
I have not yet tested this, but we should sync with @ravanelli 's patch.

**Comment by jlebon** [comment]
Minor: in the commit title, shouldn't it be s/xxd/cut/?

Ahh I see, you're just matching the PR we're syncing with. Though I guess part of the story here is that we hadn't matched the intermediate state [where `cut` was reverted back to `xxd`](https://github.com/GoogleCloudPlatform/guest-configs/pull/54) upstream. Maybe a better title would be

> google_nvme_id: sync with latest upstream version

And include the upstream PR links in the description.

But, LGTM as is too!

/approve

**Comment by HuijingHei** [comment]
Thanks @jlebon for the review, update is done.

**Comment by HuijingHei** [comment]
One more question (not related to the bug), is there any plan to put `google-compute-engine-guest-configs-udev` rpm in RHEL ?

**Comment by jlebon** [comment]
/lgtm

> One more question (not related to this issue), is there any plan to put `google-compute-engine-guest-configs-udev` rpm in RHEL ?

I'm not sure. I still don't see even just the main package in either RHEL or CentOS Stream.

**Comment by travier** [comment]
It would be great to have the package in RHEL but this hasn't happened yet.

**Pull request merged**
