### PR TITLE
kola-denylist: reenable podman.dns for scos/RHCOS9

### PR DESCRIPTION
**Pull request by HuijingHei**

### CODE REVIEW

**Comment by HuijingHei** [comment]
Run `ext.config.shared.podman.dns` passed on scos and rhcos9
- build scos with new `podman-2:4.2.0-3.el9`
- build rhcos9 with new `podman-2:4.2.0-1.rhaos4.12.el8.x86_64`

**Comment by HuijingHei** [comment]
Get the following failed log, is this because of network issue?
```
Updating metadata for 'rhel-8-server-ose'...done
error: Updating rpm-md repo 'rhel-8-server-ose': cannot update repo 'rhel-8-server-ose': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for http://base-4-12-rhel86.ocp.svc.cluster.local/rhel-8-server-ose/repodata/repomd.xml [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
error: failed to execute cmd-fetch: exit status 1
```

**Comment by travier** [comment]
Seems likely. I've merged this one into https://github.com/openshift/os/pull/978.
/close

**Pull request closed without merging**
