### PR TITLE
OCPBUGS-11791: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by ravanelli**
```
    Renata Ravanelli (2):
          overlay.d: Add 30gcp-udev-rules dracut module
          kola: Add files to be verified in initrd test
```

### CODE REVIEW

**Comment by travier** [comment]
/label backport-risk-assessed
/label cherry-pick-approved

We'll either need a valid bug label override for this one or we'll need to have it land in an RHCOS boot image bump to satisfy the bot.

**Comment by travier** [comment]
Hum, what's pulling this overlay in RHCOS? I don't see that in this commit not in the repo so far. Am I missing something?

**Comment by jlebon** [comment]
> Hum, what's pulling this overlay in RHCOS? I don't see that in this commit not in the repo so far. Am I missing something?

I think you're right. It seems like we're missing a symlink in `overlay.d/` to the overlay in the FCOS submodule (and adding it to the manifest).

An example overlay doing something similar to what we want here is `25azure-udev-rules`. Maybe let's fix that in `master` and then backport it as part of this PR?

**Comment by travier** [comment]
/hold
Pending backport of https://github.com/openshift/os/pull/1267 and testing.

**Comment by ravanelli** [comment]
> /hold Pending backport of #1267 and testing.

Backport: https://github.com/openshift/os/pull/1272
Tests:  Update the bump to include it

**Comment by ravanelli** [comment]
/bugzilla/valid-bug

**Pull request merged**
