### PR TITLE
[4.9] Change repo names to match the RHCOS repo names

### PR DESCRIPTION
**Pull request by ravanelli**
- We are changing the repo names in order to improve our internal redhat-coreos repo, to use a single branch for the RHCOS versions.

Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by jlebon** [comment]
This one still needs a corresponding openshift/release PR to update the repo names first, I think?

**Review by travier — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
