### PR TITLE
[release-4.16] OCPBUGS-36147: Bump fedora-coreos-config

### PR DESCRIPTION
**Pull request by coreosbot-releng**
Created by [GitHub workflow](https://github.com/coreos/fedora-coreos-config/actions/workflows/openshift-os.yml) ([source](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/.github/workflows/openshift-os.yml)).

```
Jonathan Lebon (2):
      growfs: set PKNAME and partnum in multipath path
      growfs: workaround sfdisk + LUKS incompatibility on 512e disks
```

### CODE REVIEW

**Comment by travier** [comment]
/retitle [release-4.16] OCPBUGS-36147: Bump fedora-coreos-config

**Comment by travier** [comment]
```
Error: Parsing metadata from src/config/tests/kola/shared/root-reprovision/luks/512e/test.sh: yaml: unmarshal errors:
  line 25: field primaryDisk not found in type kola.externalTestMeta
2024-06-25T09:37:52Z cli: Parsing metadata from src/config/tests/kola/shared/root-reprovision/luks/512e/test.sh: yaml: unmarshal errors:
  line 25: field primaryDisk not found in type kola.externalTestMeta
failed to execute cmd-kola: exit status 1
```

Needs a backport of https://github.com/coreos/coreos-assembler/pull/3822

**Comment by jlebon** [comment]
Hmm weird, still seems to be using a stale 4.16 cosa.

**Review by marmijo — APPROVED** [review]

**Comment by jlebon** [comment]
Logs for ci/prow/images shows

```
FROM image-registry.openshift-image-registry.svc:5000/ci-op-0yq7b11x/pipeline@sha256:45edfa461413c22e52c9094f7220250512c43d753a21bde72964661350ff097b
```

which matches

```
$ skopeo inspect --no-tags docker://quay.io/coreos-assembler/coreos-assembler:rhcos-4.16 | jq .Digest
"sha256:45edfa461413c22e52c9094f7220250512c43d753a21bde72964661350ff097b"
```

So `rhcos-9-build-test-qemu` should pass now.

I'm honestly confused by the mess in openshift/release related to the coreos-assembler image. There's references there and in the logs here that there's a :4.16 tag in the `coreos/coreos-assembler` imagestream, but I don't see that in either https://console.build02.ci.openshift.org/k8s/ns/coreos/imagestreams/coreos-assembler or https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/k8s/ns/coreos/imagestreams/coreos-assembler.

**Pull request merged**
